crashed|egyptair flight 990|subj
crashed|october 31 , 1999|on
departing|egyptair flight 990|subj
departing|jfk airport|obj
dropped|plane|subj
speed|near|mod
speed|supersonic|mod
dropped|speed|at
meters|9,000|num
speed|meters|for
climbed|then|mod-before
meters|climbed|vrel
climbed|meters|obj
meters|2,400|num
climbed|meters|for
meters|falling|before
falling|plane|subj
falling|and|punc
falling|breaking|conj
breaking|plane|subj
breaking|apart|mod
reports|radio|mod
were|reports|pred
reports|trouble|of
speculation|initial|mod
centered on|speculation|subj
reverser|thrust|nn
centered on|reverser|obj
reverser|(|punc
reverser|deactivated|vrel
deactivated|reverser|obj
deactivated|cairo|in
recorder|flight|nn
recovered|recorder|obj
recovered|november 9|on
recovered|and|punc
recovered|revealed|conj
revealed|recorder|subj
revealed|that|c
disconnected|autopilot|obj
appeared|descent|subj
turned off|cockpit|subj
turned off|engines|obj
were|out of|pred
were|unison|out of
failure|on-board|mod
failure|computer|nn
speculated|stopping|mod-before
stopping|failure|subj
stopping|transponder|obj
stopping|and|punc
stopping|providing|conj
providing|failure|subj
data|erroneous|mod
providing|data|obj
speculated|failure|obj
act|criminal|mod
act|involving|rel
involving|act|subj
involving|hijacking|obj
hijacking|suicide|conj
suicide|or|punc
fight|crew|nn
suicide|fight|conj
possible|also|mod
was|possible|pred
background|medical history|conj
medical history|and|punc
stability|emotional|mod
medical history|stability|conj
stability|passengers|of
passengers|and|punc
passengers|crew|conj
examined|background|obj
recorder|cockpit|nn
recorder|voice|nn
recovered|recorder|obj
recovered|november 15|on
contained|it|subj
chanting|co-pilot|nn
contained|chanting|obj
rely on|i|subj
rely on|god|obj
god|"|punc
god|and|punc
god|pilot|conj
pilot|ordering|rel
ordering|pilot|subj
ordering|actions|obj
actions|control|rel
control|action|subj
control|aircraft|obj
stated|national transportation safety board|subj
stated|on|guest
stated|january 21 , 2000|on
stated|that|c
was|sign|pred
failure|mechanical|mod
sign|failure|of
officials|egyptian|mod
continued|officials|subj
continued|seek|mod
seek|official|subj
causes|other|mod
causes|possible|mod
seek|causes|obj
triangle|"|punc
triangle|death|of
death|"|punc
death|atlantic|over
blamed|triangle|obj
something|then|mod
something|"|punc
happened|something|subj
happened|"|punc
happened|tail|to
were|august|in
were|rumors|pred
rumors|that|whn
classified|rumors|subj
classified|radar|obj
radar|showed|vrel
showed|radar|obj1
returns|three|nn
returns|high-speed|mod
showed|returns|obj2
returns|area|in
area|path|along
path|flight|of
reported|pilots|subj
reported|seeing|fc
seeing|pilot|subj
seeing|fireballs|obj
fireballs|area|in
times|different|mod
area|times|at
continued|egyptians|subj
continued|blame|mod
blame|egyptian|subj
problems|technical|mod
blame|problems|obj
problems|primarily|appo-mod
system|elevator|nn
system|control|nn
problems|system|appo
speculated|september|in
shutdown|computer|nn
shutdown|caused|vrel
caused|shutdown|obj
caused|by|by-subj
interference|electromagnetic|mod
caused|interference|by
radars|military|mod
interference|radars|from
speculated|shutdown|obj
