concorde|supersonic|mod
concorde|transport|nn
development|joint|mod
development|anglo-french|nn
was|development|pred
development|begun|vrel
begun|development|obj
begun|1962|in
size|and|punc
size|design|conj
design|concorde|of
concorde|allowed|vrel
allowed|concorde|obj
seats|only|pre
seats|100|num
seats|passenger|nn
allowed|seats|for
twenty|transports|of
built|twenty|obj
british airways|only|mod
british airways|and|punc
british airways|air france|conj
flew|british airways|subj
flew|them|obj
flight|first|post
flight|passenger|nn
was|in|pred
was|january 1976|in
crew|nine|nn
crew|person|nn
provided|crew|subj
service|luxury|mod
provided|service|obj
service|and|punc
food|gourmet|nn
service|food|conj
provided|and|punc
provided|drink|conj
drink|crew|subj
make|concorde|subj
make|flight|obj
flight|new york|between
new york|and|punc
new york|london|conj
london|or|punc
london|paris|conj
four|less than|num-mod
hours|four|amount-value
paris|hours|in
make|and|punc
set|once|mod-before
make|set|conj
set|concorde|subj
set|record|obj1
record|doing|by
set|it|obj2
three|less than|num-mod
fly over|only|amod
fly over|concorde|subj
areas|ocean|nn
fly over|areas|obj
areas|problems|because of
cause|sonic booms|subj
cause|over|guest
areas|land|nn
cause|areas|obj
travel|concorde|on
appealed|travel|subj
rich|and|punc
rich|famous|conj
schedule|tight|mod
businessmen|schedule|on
capacity|low|mod
capacity|passenger|nn
capacity|limitations|conj
limitations|routes|on
routes|and|punc
costs|high|mod
routes|costs|conj
prevented|capacity|subj
prevented|concorde|obj
becoming|ever|amod
concorde|becoming|from
becoming|capacity|subj
factor|significant|mod
becoming|factor|obj
factor|aviation|in
had|concorde|subj
record|impeccable|mod
record|safety|nn
had|record|obj
record|july 25 , 2000 ,|until
had|when|wha
af4590|air france|nn
af4590|charter|nn
af4590|flight|nn
crashed|af4590|subj
two|less than|num-mod
minutes|two|amount-value
crashed|minutes|obj
minutes|taking off|after
taking off|af4590|subj
taking off|from|guest
taking off|charles|from
gaulle airport|de|nn
taking off|gaulle airport|obj
all|109|num
all|aircraft|aboard
aircraft|most|whn
most|aircraft|of
tourists|german|mod
were|tourists|pred
tourists|and|punc
persons|four|nn
tourists|persons|conj
site|crash|nn
persons|site|at
died|all|subj
air france|and|punc
air france|british airways|conj
cancelled|immediately|mod-before
cancelled|air france|subj
cancelled|all|guest
flights|concorde|nn
cancelled|flights|obj
resumed|british airways|subj
resumed|them|obj
day|next|post
resumed|day|mod
are|that|c
metal|scrap|mod
piece|metal|of
metal|runway|on
punctured|piece|subj
punctured|tire|obj
tire|chunks|whn
chunks|tire|of
ruptured|chunks|subj
tank|fuel|nn
ruptured|tank|obj
engines|two|nn
tank|engines|next to
engines|which|whn
ignited|engines|subj
ignited|escaping|mod
escaping|piece|subj
escaping|fuel|obj
