populations|salmon|nn
decline|populations|of
coasts|pacific|nn
populations|coasts|off
coasts|united states|of
united states|and|punc
united states|canada|conj
is|one|pred
disasters|20th century|gen
disasters|environmental|mod
one|disasters|of
set|1999|in
federal government|acting|pnmod
acting|endangered species act|under
set|federal government|subj
set|in|guest
set|motion|in
plan|regional|mod
set|plan|obj
plan|restore|rel
restore|plan|subj
runs|salmon|nn
restore|runs|obj
northwest|pacific|nn
runs|northwest|in
us|and|punc
us|canada|conj
announced|us|subj
announced|plan|obj
plan|limit|comp1
limit|the us|subj
catches|salmon|nn
limit|catches|obj
limit|and|punc
limit|establish|conj
establish|the us|subj
establish|fund|obj
fund|protect|rel
protect|fund|subj
protect|fish|obj
were|agreement|prior to
countries|two|nn
were|at|pred
were|odds|at
fishing|salmon|nn
odds|fishing|on
accused|canada|subj
accused|us|obj
us|failing|of
failing|canada|subj
failing|honor|fc
honor|pacific salmon treaty|obj
pacific salmon treaty|1985|of
honor|by|mod
by|fishing|over
attempted|canadian province british columbia|subj
attempted|sue|fc
sue|canadian province british columbia|subj
government|us|nn
sue|government|obj
dams|three|nn
dams|columbia river|nn
operators|dams|of
agreed|operators|subj
administration|clinton|nn
agreed|administration|with
plan|50-year|nn
plan|preservation|nn
administration|plan|on
plan|saving|for
saving|operator|subj
saving|salmon|obj
requirement|major|mod
is|that|c
operated|dams|obj
loss|net|mod
operated|loss|with
loss|salmon|of
dams|parts|in
parts|northwest|of
are|made|pred
fish|more|mod
made|fish|desc
are|taken|pred
taken|thwart|mod
thwart|predators|obj
predators|seagulls|like
seagulls|and|punc
seagulls|squawfish|conj
squawfish|feasting|from
salmon|immature|mod
feasting|salmon|on
limits|catch|nn
imposed|limits|obj
undertaken|prosecutions|obj
egregious|most|mod
chemicals|egregious|mod
chemicals|toxic|mod
undertaken|chemicals|against
chemicals|dumping|rel
dumping|chemical|subj
dumping|rivers|in
rivers|and|punc
rivers|streams|conj
agree|experts|subj
agree|that|c
effective|most|mod
remedy|effective|mod
plight|salmon|gen
remedy|plight|for
is|breaching|pred
breaching|dams|of
dams|spawning|on
spawning|remedy|subj
spawning|rivers|obj
dams|california|in
removed|dams|obj
removed|by|by-subj
removed|2001|by
negotiated|also|mod-before
negotiated|state|subj
plan|habitat|nn
plan|conservation|nn
negotiated|plan|obj
lumber|pacific|nn
plan|lumber|with
lumber|stop|rel
stop|lumber|subj
stop|logging|obj
logging|adjacent|pnmod
adjacent|streams|to
stop|when|wha
spawn|coho salmon|subj
