's|tenth|on
anniversary|myanmar|of
takeover|military|mod
's|takeover|pred
dissidents|protested|vrel
protested|dissidents|obj
protested|bangkok|in
bangkok|and|punc
bangkok|bangladesh|conj
junta|led|vrel
led|junta|obj
led|by|by-subj
led|general|by
general|than shwe|person
rejected|junta|subj
appeals|nld|gen
appeals|repeated|mod
rejected|appeals|obj
appeals|talks|for
threatened|regime|subj
vice chairman|nld|nn
threatened|vice chairman|obj
vice chairman|tin oo|person
vice chairman|arrest|with
pressured|britain|subj
pressured|regime|obj
regime|hold|rel
hold|regime|subj
hold|talks|obj
talks|and|punc
talks|us|conj
placed|eu|subj
sanctions|economic|mod
placed|sanctions|obj
sanctions|myanmar|on
myanmar|encourage|rel
encourage|myanmar|subj
encourage|negotiations|obj
us|and|punc
countries|european|nn
us|countries|conj
boycotted|us|subj
international heroin conference|4th|mod
boycotted|international heroin conference|obj
boycotted|there|mod
trafficking|its|gen
trafficking|drug|nn
boycotted|trafficking|because of
trafficking|and|punc
record|poor|mod
record|human rights|nn
trafficking|record|conj
become|myanmar|subj
source|world|gen
source|leading|mod
become|source|obj
source|heroin|of
heroin|and|punc
heroin|epicenter|conj
crisis|regional|mod
crisis|aids|nn
epicenter|crisis|of
