late|1998|in
bank|romania|gen
bank|central|nn
is|include|pred
include|euro|obj
rates|posted|mod
rates|hard|mod
rates|currency|nn
rates|exchange|nn
euro|rates|in
include|and|punc
include|perform|conj
perform|services|obj
services|euro|in
indian|reserve bank of india|nn
indian|permits|nn
banks|indian|subj
banks|do|mod
do|indian|subj
transactions|euro|nn
do|transactions|obj
currency|bulgaria|gen
currency|national|mod
backed|formally|amod
backed|currency|obj
backed|by|by-subj
backed|euros|by
france|finland|conj
finland|belgium|conj
belgium|and|punc
belgium|spain|conj
begun|france|subj
begun|production|obj
production|euros|of
preparing|germany|subj
preparing|do|mod
do|germany|subj
do|so|obj
currency|single|mod
currency|european|mod
poses|currency|subj
poses|problems|obj
problems|vatican city|for
vatican city|and|punc
vatican city|san marino|conj
san marino|which|whn
use|san marino|subj
lire|italian|mod
use|lire|obj
lire|and|punc
lire|monaco|conj
st. pierre and miquelon|which|whn
use|st. pierre and miquelon|subj
francs|french|nn
use|francs|obj
nations|two|nn
nations|eu|nn
make|nations|subj
provisions|legal|mod
make|provisions|obj
provisions|states|for
states|use|rel
use|state|subj
use|euros|obj
