add|(|punc
attention deficit disorder|add|abbrev
add|)|punc
attention deficit disorder|and|punc
attention deficit disorder|attention deficit hyperactive disorder|conj
adhd|(|punc
attention deficit hyperactive disorder|adhd|abbrev
adhd|)|punc
disorders|neurological|mod
neurological|and|punc
neurological|genetic|conj
are|disorders|pred
disorders|that|whn
are|evident|pred
evident|childhood|in
are|and|punc
are|continue|conj
continue|disorders|subj
continue|adulthood|through
onset|adhd|of
does|not|neg
occur|onset|subj
occur|adulthood|in
have|girls|subj
have|type a|obj
type a|characterized|vrel
characterized|type a|obj
characterized|by|by-subj
characterized|inattentiveness|by
inattentiveness|and|punc
inattentiveness|distractibility|conj
have|boys|subj
have|type b|obj
have|and|punc
have|are|conj
are|hyperactive|pred
hyperactive|and|punc
hyperactive|impulsive|conj
estimated|it|obj
have|three to five|from
three to five|or|punc
nine percent|even|mod
three to five|nine percent|conj
nine percent|children|of
have|that|subj
have|disorder|obj
disorder|which|whn
outgrow|disorder|obj
outgrow|twenty percent|subj
diagnosed|add/adhd|obj
patterns|behavioral|mod
diagnosed|patterns|through
patterns|but|punc
patterns|many|conj
many|those|of
concentration|high|mod
have|concentration|obj
protein|key|mod
protein|brain|nn
concentration|protein|of
transporter|dopamine|nn
protein|transporter|appo
transporter|which|whn
lead to|transporter|subj
diagnosis|clinical|mod
lead to|diagnosis|obj
clinic|associated|pnmod
associated|university of tennessee|with
claims|clinic|subj
test|involving|rel
involving|test|subj
involving|monitoring|guest
monitoring|front|obj
involving|region|obj
region|brain|of
claims|is|fc
is|90%|pred
90%|effective|pnmod
effective|diagnosis|in
increase|number|in
number|diagnoses|of
diagnoses|adhd|of
attributed|increase|obj
attributed|include|mod
include|increase|subj
include|either|punc
include|hyperactivity|obj
hyperactivity|or|punc
behavior|impulsive|mod
hyperactivity|behavior|conj
both|necessarily|mod
ritalin|drug|nn
widely|most|mod
prescribed|widely|mod
medication|prescribed|mod
is|medication|pred
medication|control|rel
control|medication|subj
control|behavior|obj
behavior|add/adhd|of
adderall|drug|nn
used|adderall|obj
extent|lesser|mod
used|extent|to
prozac|even|mod
prescribed|prozac|obj
use|drugs|of
drugs|treat|rel
treat|drug|subj
treat|add/adhd|obj
controversial|highly|mod
is|controversial|pred
say|critics|subj
say|that|c
quick|too|mod
are|quick|pred
are|diagnose|mod
diagnose|doctor|subj
diagnose|adhd|obj
adhd|and|punc
drugs|over-prescribe|mod
adhd|drugs|conj
drugs|children|for
has|ritalin|subj
effects|side|nn
has|effects|obj
effects|including|rel
including|effect|subj
including|sleeplessness|obj
sleeplessness|and|punc
sleeplessness|loss|conj
loss|appetite|of
use|its|gen
controls|use|subj
controls|behavior|obj
found|yet|amod
found|drug|obj
found|treat|mod
treat|drug|subj
treat|disorder|obj
