surpluses|us|nn
surpluses|federal|mod
surpluses|budget|nn
surpluses|achieved|vrel
achieved|surpluses|obj
achieved|late 1990s|in
were|result|pred
discipline|fiscal|mod
result|discipline|of
discipline|imposed|vrel
imposed|discipline|obj
deficits|huge|mod
imposed|deficits|after
decade|previous|mod
deficits|decade|of
robert rubin|treasury secretary|nn
credited|robert rubin|obj
management|strong|mod
management|fiscal|mod
credited|management|with
chairman|federal reserve|nn
chairman|alan greenspan|person
kept|chairman|subj
rates|interest|nn
kept|rates|obj
kept|low|mod
market|strong|mod
market|job|nn
inflation|low|mod
market|inflation|conj
inflation|and|punc
productivity|high|mod
inflation|productivity|conj
were|factors|pred
factors|boosting|rel
boosting|factor|subj
boosting|surplus|obj
booming|wall street|subj
getting|investors|subj
getting|richer|desc
getting|and|punc
getting|increasing|conj
increasing|investors|subj
base|tax|nn
increasing|base|obj
appeared|to|guest
appeared|economists|to
appeared|that|c
surpluses|budget|nn
era|surpluses|of
was|at|pred
was|hand|at
expected|surpluses|obj
years|15|num
expected|years|mod
expected|ahead|mod
congressional budget office|1995|in
years|projected|mod
years|deficits|nn
years|ten|amount-value
predicting|1998|subj
surplus|$100 billion|nn
predicting|surplus|obj
surplus|2005|for
but|projected|comp1
projected|they|subj
projected|$100|obj
deficit|200 billion|nn
deficit|1997|for
1997|that|whn
turned into|1997|subj
turned into|$100|obj
surplus|200 billion|nn
casting|thus|amod
surplus|casting|rel
casting|surplus|subj
casting|doubt|obj
ability|its|gen
ability|forecasting|nn
doubt|ability|on
existence|surplus|of
had|naturally|mod-before
had|existence|subj
had|politicians|obj
politicians|proposing|rel
proposing|politician|subj
proposing|ways|obj
ways|spend|rel
spend|way|subj
spend|it|obj
called for|clinton administration|subj
called for|social security|obj
social security|and|punc
funding|medicaid|nn
social security|funding|conj
funding|retirement|conj
retirement|saving|rel
saving|retirement|subj
saving|accounts|obj
accounts|and|punc
readiness|military|mod
accounts|readiness|conj
wanted|liberals|subj
spending|more|mod
wanted|spending|obj
spending|education|on
technology|basic|mod
education|technology|conj
research|medical|mod
technology|research|conj
research|and|punc
research|transportation|conj
chairman|greenspan|person
signed|initially|mod-before
signed|chairman|subj
finding|social security|nn
signed|finding|onto
signed|but|punc
argued|later|amod
signed|argued|conj
argued|chairman|subj
reduction|debt|nn
argued|reduction|for
all|republicans|nn
called for|all|subj
cuts|tax|nn
called for|cuts|obj
republican|one|nn
republican|prominent|mod
republican|house|nn
argued|republican|subj
argued|that|c
taxes|all|pre
be|except for|mod-before
tax|payroll|nn
be|tax|except for
be|cut|pred
chairman|greenspan|person
said|chairman|subj
said|that|c
cut|tax|nn
suited|better|amod
suited|cut|obj
suited|time|for
suited|when|wha
turned|economy|subj
turned|down|mod
