began|1996|in
began|china|subj
began|cracking down on|mod
cracking down on|china|subj
cracking down on|crime|obj
investigations|extensive|mod
investigations|and|punc
tips|citizen|nn
investigations|tips|conj
led to|investigations|subj
led to|hundreds|obj
hundreds|arrests|of
crimes|such|pre
arrests|crimes|for
trafficking|drug|nn
crimes|trafficking|as
firearms|ammunition|conj
ammunition|and|punc
manufacturing|explosives|nn
ammunition|manufacturing|conj
manufacturing|sales|conj
sales|smuggling|conj
smuggling|and|punc
smuggling|possession|conj
burglary|and|punc
burglary|robbery|conj
are|often|guest
are|gangs|pred
gangs|thieves|of
thieves|and|punc
thieves|criminals|conj
criminals|and|punc
criminals|members|conj
gangs|international|mod
gangs|criminal|nn
members|gangs|of
gangs|operating|rel
operating|gang|subj
operating|china|between
china|and|punc
china|hong kong|conj
hong kong|or|punc
hong kong|china|conj
china|and|punc
china|macau|conj
were|1998|in
suspects|criminal|mod
60%|suspects|of
were|minors|pred
authorities|chinese|nn
broke up|authorities|subj
gang|hong kong-based|mod
broke up|gang|obj
gang|operating|rel
operating|gang|subj
operating|hong kong|between
hong kong|and|punc
hong kong|mainland|conj
leader|its|gen
tried|leader|obj
tried|death|to
death|china|in
authorities|chinese|nn
apprehended|authorities|subj
apprehended|members|obj
gang|macau|nn
members|gang|of
guangdong province|its|gen
gang|guangdong province|in
agreed|part|as
campaign|its|gen
campaign|"|punc
campaign|strike hard|nn
campaign|national|mod
campaign|crime-fighting|mod
part|campaign|of
agreed|china|subj
agreed|participate|fc
participate|china|subj
participate|un commission on crime prevention|in
un commission on crime prevention|and|punc
justice|criminal|mod
un commission on crime prevention|justice|conj
revised|china|subj
criminal|its|gen
revised|criminal|obj
criminal|and|punc
laws|procedural|mod
criminal|laws|conj
revised|and|punc
revised|enacted|conj
enacted|china|subj
laws|new|mod
enacted|laws|obj
law|its|gen
law|criminal|nn
amended|law|obj
amended|include|mod
include|law|subj
crime|terrorist|mod
include|crime|obj
crime|organized crime|conj
organized crime|money-laundering|conj
trafficking|illegal|mod
trafficking|immigrant|nn
money-laundering|trafficking|conj
trafficking|and|punc
crimes|environment-related|mod
trafficking|crimes|conj
signed|china|subj
agreements|legal|mod
agreements|assistance|nn
signed|agreements|obj
countries|28|num
agreements|countries|with
countries|and|punc
agreements|extradition|nn
countries|agreements|conj
agreements|ten|with
cross-border|china|nn
cross-border|pledged|mod
cross-border|increased|mod
cooperation|anti-crime|mod
portugal|take|rel
take|portugal|subj
measures|tougher|mod
take|measures|obj
crime|gang-related|mod
measures|crime|against
crime|preparation|in
handover|1999|num
preparation|handover|for
colony|portuguese|nn
handover|colony|of
station|handover|after
station|china|subj
station|troops|obj
troops|macau|in
fight|better|amod
macau|fight|rel
fight|macau|subj
activity|organized|mod
activity|criminal|mod
fight|activity|obj
fight|there|mod
pledges|chinese|nn
pledges|government|nn
pledges|increase|rel
increase|pledge|subj
increase|efforts|obj
efforts|crack down on|rel
crack down on|effort|subj
crack down on|corruption|obj
corruption|smuggling|conj
smuggling|and|punc
crimes|other|mod
crimes|economic|mod
smuggling|crimes|conj
crimes|as|punc
crimes|well|punc
crimes|as|punc
acts|criminal|mod
crimes|acts|conj
acts|2000|in
