supersonic|only|mod
plane--|supersonic|mod
plane--|passenger|nn
plane--|crashed|rel
crashed|plane--|obj
crashed|concorde--|subj
crashed|july 25 , 2000 ,|on
crashed|killing|mod
killing|concorde--|subj
killing|all|obj
all|109|num
all|board|on
board|and|punc
board|4|conj
4|ground|on
agreement|developed|mod
developed|french|by
french|and|punc
french|british|conj
british|1962|under
made|it|subj
flight|its|gen
flight|first|post
flight|passenger|nn
made|flight|obj
flight|1976|in
planes|twenty|nn
built|planes|obj
were|still|guest
were|flying|pred
flying|2000|in
flight|roundtrip|nn
cost|flight|subj
cost|$10,000|obj
had|plane|subj
seats|100|num
had|seats|obj
had|and|punc
had|flew|conj
flew|plane|subj
mph|1,300|num
flew|mph|obj
feet|60,000|num
mph|feet|at
took|it|subj
took|less|guest
took|4|obj
hours|cross|rel
cross|hour|subj
cross|atlantic|obj
took|carrying|mod
carrying|hours|subj
people|famous|mod
famous|and|punc
famous|business|conj
started|it|subj
started|out|guest
miracle|technological|mod
started|miracle|obj
started|but|punc
started|became|conj
became|it|subj
disaster|economic|mod
became|disaster|obj
disaster|and|punc
artifact|elegant|mod
artifact|cultural|mod
disaster|artifact|conj
artifact|20th century|of
caused|crash|obj
caused|by|by-subj
caused|piece|by
falling off|metal|mod
piece|falling off|of
falling off|continental dc10|of
continental dc10|that|whn
used|continental dc10|subj
used|runway|obj
runway|concorde|before
cut|metal|subj
tire|concorde|gen
cut|tire|obj
rubber|flying|mod
damaged|rubber|subj
damaged|engines|obj
engines|causing|rel
causing|engine|subj
leak|fuel|nn
causing|leak|obj
leak|that|whn
burst|leak|subj
burst|flame|into
late|too|mod
burst|late|mod
burst|abort|mod
crashed|it|subj
hotel|small|mod
crashed|hotel|into
found|bodies|obj
moved|wreckage|obj
moved|reassembled|mod
opened|french|subj
opened|inquiry|obj
inquiry|place|rel
place|inquiry|subj
place|blame|obj
place|hearing|mod
witnesses|295|num
hearing|witnesses|from
all|passengers|of
were|germans|pred
germans|going|rel
going|german|subj
going|new york|to
paid|air france|subj
paid|each|guest
$20,000|family|nn
paid|$20,000|obj
$20,000|cover|rel
cover|$20,000|subj
expenses|immediate|mod
cover|expenses|obj
services|memorial|nn
held|services|obj
held|paris|in
held|cologne|in
site|crash|nn
later|site|at
grounded|immediately|mod-before
grounded|air france|subj
fleet|its|gen
grounded|fleet|obj
stopped|british airways|subj
stopped|flights|obj
flights|august 15|on
investigating|air france|subj
investigating|modifications|obj
modifications|insure|rel
insure|modification|subj
insure|safety|obj
insure|and|punc
insure|sued|conj
sued|modification|subj
sued|continental|obj
continental|september 27|on
