governor|texas|nn
governor|george w. bush|person
defended|governor|subj
penalty|death|nn
defended|penalty|obj
penalty|deterrent|as
deterrent|crime|to
defended|and|punc
defended|presided|conj
presided|governor|subj
presided|record|over
executions|143|num
years|five|amount-value
halted|years|in
halted|he|subj
one|only|mod
halted|one|obj
evidence|faulty|mod
halted|evidence|because of
halted|and|punc
halted|granted|conj
granted|he|obj1
reprieve|one 30-day|nn
granted|reprieve|obj2
based|he|subj
based|decisions|obj
decisions|doubt|on
doubt|guilt|about
guilt|and|punc
opportunity|court|nn
guilt|opportunity|conj
opportunity|reviewing|for
reviewing|he|subj
issues|legal|mod
reviewing|issues|obj
believed|he|subj
people|innocent|mod
believed|executed|fc
executed|people|obj
had|he|subj
had|right|obj
right|overturn|rel
overturn|right|subj
verdicts|jury|nn
overturn|verdicts|obj
recommend|he|subj
recommend|clemency|obj
recommend|only|mod
recommend|if|c
board of pardons|18-member|mod
board of pardons|and|punc
board of pardons|paroles|conj
paroles|all|whn
all|paroles|of
appointed|all|obj
appointed|he|subj
recommended|board of pardons|subj
recommended|it|obj
members|board|nn
held|members|subj
held|meetings|obj
held|and|punc
held|voted|conj
voted|members|subj
voted|fax|by
fax|or|punc
fax|telephone|conj
opposed|bush|subj
meetings|public|mod
meetings|clemency|nn
opposed|meetings|obj
meetings|opportunities|as
speeded|bush|subj
process|appeals|nn
speeded|process|obj
process|opposed|vrel
opposed|process|obj
opposed|barring|mod
barring|bush|subj
barring|execution|obj
execution|mentally retarded|of
barring|vetoed|conj
vetoed|bush|subj
vetoed|creation|obj
systems|impartial|mod
systems|public defender|nn
creation|systems|of
vetoed|and|punc
vetoed|said|conj
said|bush|subj
said|favored|fc
favored|he|subj
testing|dna|nn
favored|testing|obj
favored|but|punc
did|not|neg
favored|push|conj
push|he|subj
push|require|mod
require|he|subj
require|it|obj
process|texas|gen
process|clemency|nn
criticized|process|obj
criticized|widely|mod
widely|violating|as
violating|process|subj
safeguards|minimum|mod
violating|safeguards|obj
rights|human|nn
safeguards|rights|for
board|parole|nn
described|board|obj
described|as|mod
hostile|secretive|conj
secretive|unconstitutional|conj
unconstitutional|unfair|conj
defendants|indigent|mod
unfair|defendants|to
unfair|and|punc
unfair|interested|conj
described|only|mod
only|preserving|in
preserving|board|subj
preserving|system|obj
system|and|punc
system|illusion|conj
illusion|review|of
are|undocumented|pred
are|so|mod
so|is|comp1
is|way|pred
way|determine|rel
determine|way|subj
determine|whether|c
is|arbitrary|pred
is|or|punc
is|meets|conj
meets|voting|subj
requirements|due process|nn
meets|requirements|obj
forwarded|letters|obj
members|board|nn
forwarded|members|to
pope|and|punc
pope|others|conj
asked|unsuccessfully|mod-before
asked|pope|subj
asked|bush|obj1
bush|stay|rel
stay|bush|subj
asked|executions|obj2
citizen|canadian|mod
executions|citizen|for
woman|born-again|mod
citizen|woman|appo
criticized|bush|obj
criticized|callousness|for
criticized|and|punc
criticized|disengaged|conj
disengaged|bush|obj
supports|still|mod-before
supports|public|subj
penalty|death|nn
supports|penalty|obj
shrinking|support|subj
shrinking|dramatically|mod
