americans|low-income|mod
face|americans|subj
face|problems|obj
problems|finding|in
finding|american|subj
finding|housing|obj
finding|because|mod
numbers|their|gen
because|increased|comp1
increased|numbers|subj
decades|last|post
decades|two|amount-value
increased|decades|over
increased|while|mod
housing|affordable|mod
pool|housing|of
while|shrunk|comp1
shrunk|pool|subj
dropped out|landlords|subj
programs|subsidy|nn
dropped out|programs|of
closed|properties|obj
closed|age|because of
closed|or|punc
closed|razed|conj
razed|properties|obj
kept up with|wages|subj
rises|housing|nn
rises|cost|nn
kept up with|rises|obj
rises|driven|vrel
driven|rises|obj
driven|by|by-subj
economy|strong|mod
driven|economy|by
increased|jobs|subj
increased|suburbs|in
housing|affordable|mod
suburbs|housing|with
housing|and|punc
housing|transportation|conj
refused|congress|subj
assistance|new|mod
refused|assistance|obj1
refused|vouchers|obj2
vouchers|1995-1998|between
turnover|public|mod
turnover|housing|nn
is|low|pred
lists|waiting|nn
are|long|pred
housing|public|mod
concentrates|housing|subj
poor|extremely|mod
people|poor|mod
concentrates|people|obj
concentrates|sapping|mod
sapping|housing|subj
vitality|commercial|mod
sapping|vitality|obj
sapping|and|punc
sapping|fostering|conj
fostering|housing|subj
segregation|racial|mod
racial|and|punc
racial|economic|conj
fostering|segregation|obj
applicants|minority|nn
applicants|mortgage|nn
face|applicants|subj
face|discrimination|obj
homes|sterile|mod
homes|nursing|nn
homes|lack|for
alternatives|affordable|mod
lack|alternatives|of
efforts|address|comp1
address|problems|obj
updating|1937|guest
law|public|mod
law|housing|nn
updating|law|obj
required|1977|in
required|banks|obj
required|loan|mod
loan|bank|subj
loan|money|obj1
money|low-income|to
low-income|and|punc
low-income|minority|conj
loan|residents|obj2
residents|where|wha
did|they|subj
did|business|obj
measures|real|mod
real|or|punc
real|proposed|conj
include|measures|subj
grants|block|nn
include|grants|obj
grants|states|to
assistance|housing|nn
states|assistance|for
availability|greater|mod
assistance|availability|conj
subsidies|rent|nn
availability|subsidies|of
subsidies|and|punc
insured|federally|mod
mortgages|insured|mod
subsidies|mortgages|conj
mortgages|use|conj
vouchers|rent|mod
use|vouchers|of
vouchers|help|rel
help|voucher|subj
help|buy|obj
help|home|mod
vouchers|and|punc
vouchers|incentives|conj
incentives|or|punc
incentives|requirements|conj
requirements|keep|rel
keep|requirement|subj
keep|landlords|obj
programs|subsidy|nn
landlords|programs|in
keep|and|punc
keep|encourage|conj
encourage|requirement|subj
encourage|creation|obj
units|subsidized|mod
units|housing|nn
creation|units|of
economic|better|mod
mix|economic|mod
provide|mix|obj
set|to|mod-before
projects|housing|nn
set|projects|to
limits|relaxed|mod
limits|income|nn
projects|limits|through
set|units|obj
lists|waiting|nn
set|lists|on
real estate investment trusts|specializing|rel
specializing|real estate investment trusts|subj
housing|affordable|mod
specializing|housing|in
established|real estate investment trusts|obj
proposed|it|obj
revenues|fha|nn
reserved|revenues|obj
reserved|use|for
initiatives|federal|mod
initiatives|housing|nn
use|initiatives|in
