fell to|saturday , august 12 , 2000 ,|on
kursk|russia|gen
kursk|nuclear|mod
kursk|submarine|nn
fell to|kursk|subj
fell to|bottom|obj
bottom|barents sea|of
fell to|while|mod
near|training|on
waters|international|mod
mission|waters|in
while|near|comp1
near|mission|subj
near|arctic circle|obj
submarine|14,000-ton|mod
settled|submarine|subj
feet|354 to 450|nn
settled|feet|obj
settled|down|mod
settled|trapping|mod
trapping|submarine|subj
sailors|118|num
trapping|sailors|obj
causes|possible|mod
causes|accident|of
explanation|collision|nn
explanation|(|punc
explanation|favored|mod
explanation|russian|mod
were|explanation|pred
were|perhaps|mod
were|as|mod
as|rose|comp1
rose|kursk|subj
level|periscope|nn
rose|level|to
rose|)|punc
explosion|onboard|nn
explosion|(|punc
likely|most|mod
explanation|likely|mod
explosion|explanation|appo
involving|probably|amod
rose|involving|mod
involving|explosion|subj
involving|torpedo|obj
involving|and|punc
involving|triggering|conj
triggering|explosion|subj
detonations|further|mod
triggering|detonations|obj
triggering|)|punc
triggering|or|punc
triggering|hitting|conj
hitting|explosion|subj
mine|wwii|nn
hitting|mine|obj
reactors|powering|rel
powering|nuclear reactor|subj
powering|ship|obj
taken|reactors|obj
taken|line|off
line|and|punc
leaks|radiation|nn
line|leaks|conj
contact|only|mod
signals|crew|mod
signals|sos|nn
contact|signals|with
tapped|contact|subj
tapped|hull|on
hull|stopped|vrel
stopped|hull|obj
stopped|tuesday|mod
revealed|probes|subj
damage|massive|mod
revealed|damage|obj
damage|front|to
front|vessel|of
vessel|and|punc
hole|large|mod
vessel|hole|conj
hole|hull|in
efforts|repeated|mod
efforts|hook up|rel
hook up|effort|subj
hook up|air|obj
air|and|punc
lines|fuel|nn
air|lines|conj
lines|and|punc
lines|dock|conj
dock|escape hatch|with
frustrated|efforts|obj
frustrated|by|by-subj
conditions|bad|mod
conditions|sea|mod
frustrated|conditions|by
navy|russian|mod
had|navy|subj
vessels|advanced|mod
vessels|rescue|nn
had|vessels|obj
had|so|mod
offered|including|mod-before
including|country|subj
including|us|obj
so|offered|comp1
offered|countries|subj
offered|help|obj
rejected|russia|subj
offer|french|nn
rejected|offer|obj
approached|tuesday|on
approached|it|subj
approached|nato|obj
nato|help|about
about|and|punc
about|by|conj
british|wednesday|nn
british|accepted|mod
about|british|by
british|and|punc
offers|norwegian|mod
british|offers|conj
vehicles|rescue|nn
arrived|vehicles|subj
arrived|saturday|mod
operations|rescue|nn
ended|operations|subj
days|two|amount-value
later|days|amount-value
when|later|mod
ended|when|wha
opened|divers|subj
opened|hatch|obj
ended|and|punc
ended|found|conj
found|operations|subj
found|filled|fc
filled|sub|subj
filled|water|with
were|survivors|pred
government|putin|gen
criticized|government|obj
delay|its|gen
criticized|delay|for
delay|accepting|in
accepting|government|subj
accepting|help|obj
lifting|kursk|obj
kursk|surface|to
take|year|mod
take|and|punc
take|be|conj
be|costly|pred
be|and|punc
done|never|guest
be|done|conj
bodies|sailors|gen
were|retrieved|pred
retrieved|october|in
october|or|punc
october|november|conj
retrieved|by|by-subj
cutting|holes|obj
holes|hull|in
