wetlands|called|vrel
called|wetlands|obj1
kidney|earth|gen
called|kidney|desc
are|important|pred
important|filtering|in
filtering|wetlands|subj
filtering|pollutants|obj
filtering|regulating|mod
regulating|climate|obj
regulating|conserving|mod
conserving|water|obj
conserving|preventing|mod
preventing|erosion|obj
preventing|controlling|conj
controlling|floods|obj
controlling|and|punc
controlling|preserving|conj
preserving|biodiversity|obj
extensions|low-cost|mod
be|extensions|pred
plants|wastewater|nn
plants|treatment|nn
extensions|plants|of
are|of|pred
importance|vital|mod
importance|economic|mod
are|importance|of
importance|asia|to
activities|human|nn
threaten|activities|subj
threaten|wetlands|obj
wetlands|places|in
threaten|including|mod
including|activity|subj
including|asia|obj
asia|africa|conj
africa|and|punc
africa|us|conj
us|where|wha
acres|100,000|num
acres|year|per
been|lost|pred
ramsar convention|1971|num
has|aiming|mod-before
aiming|ramsar convention|subj
aiming|conserve|fc
habitats|wetland|nn
conserve|habitats|obj
conserve|and|punc
conserve|enhance|conj
cooperation|international|mod
enhance|cooperation|obj
has|ramsar convention|subj
countries|90|num
countries|signatory|nn
has|countries|obj
linked|1996|in
linked|wetlands international|subj
linked|government|obj
government|and|punc
groups|ngo|nn
government|groups|conj
groups|work|rel
work|group|subj
work|conservation|for
raising|countries|subj
awareness|public|mod
raising|awareness|obj
importance|wetlands|gen
awareness|importance|of
established|1996|in
established|uganda|subj
abuse|environmental|mod
established|abuse|obj
abuse|reporting|rel
reporting|abuse|subj
reporting|hot line|obj
reporting|and|punc
reporting|banned|conj
draining|swamps|of
swamps|development|for
established|china|subj
130|over|num-mod
reserves|130|nn
reserves|wetland|nn
reserves|nature|nn
established|reserves|obj
reserves|1982|since
reserves|and|punc
protections|increased|mod
protections|wetland|nn
reserves|protections|conj
help|international|nn
restoration|wetland|nn
help|restoration|with
come from|help|subj
come from|netherlands|obj
netherlands|finland|conj
finland|and|punc
finland|world bank|conj
us|1972|appo-mod
corps|clean water act|nn
corps|mandated|mod
us|corps|appo
regulation|engineers|nn
corps|regulation|of
regulation|wetlands|of
system|ineffective|mod
system|nationwide|mod
system|permit|nn
tightened|system|obj
tightened|1996|in
1996|require|rel
require|1996|subj
permits|individual|mod
require|permits|obj
permits|projects|for
projects|3-acres|of
3-acres|10|instead of
10|then|pnmod
half|2000|num
then|half|in
acre|and|punc
acre|one-tenth an acre|conj
watershed|ny city|nn
one-tenth an acre|watershed|in
scrutiny|closer|mod
required|scrutiny|obj
developers|who|whn
damaged|developers|subj
damaged|wetlands|obj
required|developers|obj
required|create|mod
create|developer|subj
ones|new|mod
create|ones|obj
habitat|critical|mod
declarations|habitat|of
habitat|wildlife|for
limited|also|mod-before
limited|declarations|subj
limited|development|obj
projects|illegal|mod
shut|projects|obj
shut|down|mod
shut|and|punc
shut|fined|conj
fined|projects|obj
protecting|wetlands|obj
hindered|by|by-subj
enforcement|insufficient|mod
hindered|enforcement|by
pressure|politicians|from
politicians|developers|conj
developers|and|punc
developers|industry|conj
resistance|residents|of
effects|side|nn
included|effects|subj
breeding|mosquito|nn
included|breeding|obj
breeding|and|punc
damage|beaver|nn
breeding|damage|conj
