residents|kenya|of
continue|residents|subj
continue|plagued|mod
plagued|by|by-subj
plagued|diseases|by
dysentery|typhoid|nn
malaria|dysentery|conj
dysentery|tuberculosis|conj
tuberculosis|cholera|conj
cholera|diarrhea|conj
fever|valley|nn
diarrhea|fever|conj
fever|and|punc
fever|malnutrition|conj
attacks|heart|nn
are|on|pred
are|rise|on
threat|greatest|mod
threat|life|to
life|and|punc
life|health|conj
been|however|mod-before
been|spread|pred
spread|hiv/aids|of
traditional|more|mod
traditional|"|punc
diseases|traditional|mod
diseases|"|punc
continue|diseases|subj
continue|cause|mod
cause|disease|subj
cause|death|obj
death|and|punc
sickness|lingering|mod
death|sickness|conj
impact|hiv/aids|of
raised|impact|subj
misery|kenyan|mod
raised|misery|obj
heights|new|mod
misery|heights|to
reported|it|obj
persons|500|num
die|persons|subj
die|hiv/aids|from
die|day|mod
created|hiv/aids|subj
orphans|a million|mod
created|orphans|obj
orphans|country|in
disease|dreaded|mod
advance|disease|of
lower|advance|subj
life expectancy|kenyan|gen
lower|life expectancy|obj
life expectancy|that|whn
stands|life expectancy|subj
years|58|amount-value
stands|years|as
years|1998|in
years|only|mod
years|42|amount-value
years|years|to
years|2010|by
has|gross domestic product|subj
14.5%|lost|mod
has|14.5%|obj
one|ten|of
born|children|subj
born|kenya|in
dies|now|subj
disease|preventable|mod
dies|disease|from
disease|age|before
age|five|of
die|children|subj
die|mainly|mod
mainly|malaria|from
malaria|diarrhea|conj
diarrhea|vomiting|conj
vomiting|and|punc
vomiting|malnutrition|conj
steps|positive|mod
are|taken|pred
assessing|cooperation|in
cooperation|several|with
several|its|of
kenya|african|mod
kenya|neighbors|nn
assessing|kenya|subj
assessing|magnitude|obj
magnitude|diseases|of
diseases|affecting|rel
affecting|disease|subj
affecting|it|obj
it|and|punc
countries|nearby|mod
it|countries|conj
increased|kenya|subj
increased|number|obj
number|cardiologists|of
cardiologists|treating|for
treating|kenya|subj
disease|heart|nn
treating|disease|obj
providing|they|subj
condoms|free|mod
providing|condoms|obj
condoms|stem|rel
stem|condom|subj
stem|advance|obj
advance|hiv/aids|of
drugs|-malarial|nn
replacing|drugs|subj
replacing|those|obj
effectiveness|those|gen
those|effectiveness|whn
diminished|effectiveness|subj
receiving|kenya|subj
receiving|aid|obj
aid|international organizations|from
international organizations|world bank|like
world bank|and|punc
world bank|world health organization|conj
like|and|punc
like|from|conj
like|united states|from
united states|and|punc
united states|japan|conj
most|aid|of
is|for|pred
combating|most|subj
combating|spread|obj
spread|hiv/aids|of
