mission|galileo|nn
mission|jupiter|to
exceeded|mission|subj
optimistic|most|mod
predictions|optimistic|mod
exceeded|predictions|obj
allowed|data|subj
insights|new|mod
allowed|insights|obj1
insights|our|into
formation|solar system|gen
allowed|formation|obj2
formation|and|punc
formation|evolution|conj
evolution|and|punc
evolution|origins|conj
origins|life|of
craft|first|post
is|craft|pred
craft|enter|rel
enter|craft|subj
atmosphere|planet|gen
enter|atmosphere|obj
enter|and|punc
enter|send|conj
send|craft|subj
data|back|nn
send|data|obj
found|jupiter|obj
hotter|much|mod
be|hotter|pred
hotter|and|punc
hotter|windier|conj
windier|thought|than
composition|atmospheric|mod
composition|chemical|mod
be|composition|with
resembling|closely|amod
composition|resembling|rel
resembling|composition|subj
resembling|sun|obj
energy|jupiter|gen
energy|surface|mod
comes from|energy|subj
comes from|heat|obj
heat|escaping|rel
escaping|heat|subj
escaping|deep|from
deep|planet|in
rings|jupiter|gen
rings|formed|vrel
formed|rings|obj
formed|by|by-subj
debris|cosmic|mod
formed|debris|by
debris|smashing|rel
smashing|debris|subj
smashing|moons|into
numerous|more|mod
are|numerous|pred
numerous|and|punc
numerous|complex|conj
complex|thought|than
formed|probably|amod
formed|jupiter|obj
conditions|cooler|mod
formed|conditions|under
europa|jupiter|gen
europa|moons|nn
europa|and|punc
europa|callisto|conj
contain|probably|mod-before
contain|europa|subj
oceans|subsurface|mod
oceans|salty|mod
contain|oceans|obj
support|europa|subj
forms|life|nn
support|forms|obj
europa|jupiter|gen
europa|gravity|nn
europa|changes|nn
shape|europa|gen
shape|it|as
orbits|shape|subj
core|europa|gen
is|metallic|pred
surrounded|rock|by
rock|water|conj
water|and|punc
water|ice|conj
pole|its|gen
pole|magnetic north|nn
reverses|pole|subj
has|io|subj
iron|giant|subj
iron|core|obj
core|overlain|vrel
overlain|core|obj
overlain|by|by-subj
overlain|rock|by
rock|and|punc
100|over|num-mod
volcanoes|100|nn
volcanoes|active|mod
rock|volcanoes|conj
has|ganymede|subj
magnetic field|its own|gen
has|magnetic field|obj
has|indicating|mod
indicating|ganymede|subj
indicating|fluid|obj1
core|metal|mod
indicating|core|obj2
launched|galileo|obj
atlantis|space|nn
atlantis|shuttle|nn
launched|atlantis|aboard
atlantis|october 1989|in
launched|and|punc
launched|took|conj
took|galileo|subj
years|six|amount-value
took|years|obj
years|reach|rel
reach|years|subj
reach|jupiter|obj
released|probe|obj
released|galileo|from
galileo|july 1996|in
released|entering|mod
entering|probe|subj
atmosphere|jupiter|gen
entering|atmosphere|obj
entering|december 7th|mod
entering|and|punc
entering|sending|conj
sending|probe|subj
sending|back|guest
sending|data|obj
minutes|30|amount-value
data|minutes|for
years|two|amount-value
was|years|after
years|studying|rel
studying|years|subj
studying|jupiter|obj
jupiter|and|punc
moons|its|gen
moons|four|nn
moons|largest|mod
jupiter|moons|conj
studying|1998|in
orbit|galileo|gen
was|rerigged|pred
was|focus on|mod
focus on|orbit|subj
focus on|europa|obj
more|two|nn
europa|more|for
focus on|years|mod
antenna|galileo|gen
antenna|main|mod
failed|antenna|subj
failed|unfurl|fc
unfurl|antenna|subj
began|1999|in
began|galileo|subj
began|experiencing|fc
experiencing|galileo|subj
damage|instrument|nn
experiencing|damage|obj
radiation|jupiter|gen
radiation|intense|mod
damage|radiation|from
was|2000|by
was|low|pred
debated|officials|subj
debated|cost-effectiveness|obj
operations|further|mod
cost-effectiveness|operations|of
