rescued|elian gonzales|obj
rescued|sea|at
sea|november 25 , 1999|on
mother|his|gen
he|mother|conj
mother|and|punc
others|12|num
mother|others|conj
fled|he|subj
fled|cuba|obj
cuba|motorboat|in
motorboat|that|whn
capsized|motorboat|subj
two|only|mod
survived|two|subj
great-uncle|elian|gen
great-uncle|florida|in
granted|great-uncle|obj1
custody|temporary|mod
granted|custody|obj2
father|his|gen
demanded|father|subj
return|his|gen
demanded|return|obj
return|cuba|to
applied|great-uncle|subj
applied|asylum|for
asylum|elian|for
applied|but|mod
ruled|in|mod-before
ruled|accordance|in
accordance|us|with
us|and|punc
us|international law|conj
but|ruled|comp1
ruled|immigration and naturalization service|subj
ruled|that|c
belonged|elian|subj
father|his|gen
belonged|father|with
belonged|and|punc
belonged|returned|conj
returned|elian|obj
returned|cuba|to
became|elian|subj
became|symbol|obj
struggle|continuing|mod
symbol|struggle|of
struggle|castro|between
castro|and|punc
community|us|nn
community|cuban-exile|mod
castro|community|conj
sought|sides|subj
support|popular|mod
sought|support|obj
support|and|punc
demonstrations|staged|mod
support|demonstrations|conj
demonstrations|and|punc
demonstrations|strikes|conj
countries|other|mod
countries|communist|mod
backed|countries|subj
backed|castro|obj
grandmothers|elian|gen
grandmothers|cuban|mod
visited|grandmothers|subj
visited|him|obj
visited|florida|in
florida|january|in
arrived|april|in
father|his|gen
arrived|father|subj
arrived|washington|in
made|congress|subj
made|attempts|obj
attempts|become|rel
become|attempt|subj
become|involved--|desc
become|offering|mod
offering|elian|obj
elian|and|punc
asylum|his|gen
asylum|father|nn
elian|asylum|conj
offering|and|punc
offering|discussing|conj
discussing|act|obj
act|congress|of
refused|great-uncle|subj
refused|relinquish|fc
relinquish|great-uncle|subj
relinquish|custody|obj
seized|elian|obj
seized|by|by-subj
seized|federal agents|by
seized|and|punc
seized|taken to|conj
taken to|elian|subj
father|his|gen
taken to|father|obj
father|resulting|pnmod
resulting|riots|in
riots|miami|in
great-uncle|fought|vrel
fought|great-uncle|obj
fought|courts|through
courts|retain|rel
retain|federal court|subj
retain|custody|obj
filed|he|subj
lawsuit|federal|mod
filed|lawsuit|obj
lawsuit|which|whn
dismissed|lawsuit|obj
dismissed|march|in
enjoined|elian|obj
leaving|elian|subj
leaving|united states|obj
process|appeal|nn
united states|process|during
denied|june 1|on
denied|appeal|obj
upheld|denial|obj
upheld|june 23|on
refused|june 28|on
refused|supreme court|subj
refused|review|fc
review|supreme court|subj
review|case|obj
review|or|punc
review|extend|conj
extend|supreme court|subj
extend|injunction|obj
elian|and|punc
father|his|gen
elian|father|conj
returned to|elian|subj
returned to|cuba|obj
plane|chartered|mod
cuba|plane|on
plane|that|whn
meeting with|later|amod
meeting with|plane|subj
meeting with|castro|obj
