had|united states|subj
surplus|budget|nn
had|surplus|obj
surplus|total|of
total|$423 billion|of
years|three|amount-value
$423 billion|years|for
years|1998|of
1998|1999|conj
1999|and|punc
1999|2000|conj
created|surplus|obj
created|by|by-subj
created|combination|by
package|balanced|mod
package|budget|nn
combination|package|of
package|and|punc
economy|exceptional|mod
package|economy|conj
growth|strong|mod
inflation|low|mod
growth|inflation|conj
market|strong|mod
market|job|nn
inflation|market|conj
productivity|increased|mod
market|productivity|conj
productivity|and|punc
spending|increased|mod
spending|consumer|nn
productivity|spending|conj
characterized|growth|subj
characterized|economy|obj
were|year|in
year|2000|num
were|high|pred
surpluses|future|mod
surpluses|budget|nn
high|surpluses|for
forecast|white house|subj
forecast|surplus|obj
surplus|$4|of
$4|$4.4 trillion|to
15|next|num-mod
years|15|amount-value
$4.4 trillion|years|over
predicting|congress|subj
predicting|surplus|obj
surplus|$2.6|of
$2.6|$2.9 trillion|to
10|next|num-mod
years|10|amount-value
$2.9 trillion|years|over
disparity|large|mod
was|disparity|pred
disparity|democrats|between
democrats|and|punc
democrats|republicans|conj
on|do|pcomp-c
do|surplus|with
wanted|democrats|subj
wanted|spend|fc
spend|democrat|subj
spend|money|obj
spend|and|punc
limited|only|amod
spend|limited|conj
limited|democrat|subj
cuts|tax|nn
limited|cuts|obj
wanted|they|subj
wanted|shore up|fc
shore up|they|subj
security|social|nn
shore up|security|obj
security|and|punc
security|medicare|conj
shore up|and|punc
shore up|reduce|conj
reduce|they|subj
debt|federal|mod
reduce|debt|obj
debt|goal|with
goal|debt|of
debt|2012|by
wanted|they|subj
wanted|spend|fc
spend|they|subj
spend|money|obj
training|job|nn
money|training|on
training|education|appo
education|defense--|appo
defense--|including|rel
including|defense--|subj
including|pay raise|obj
personnel|military|nn
pay raise|personnel|for
research|medical|mod
personnel|research|conj
care|improved|mod
care|health|nn
research|care|conj
construction|school|nn
care|construction|conj
construction|and|punc
construction|assistance|conj
personnel|unemployed|to
unemployed|and|punc
unemployed|those|conj
incomes|low|mod
those|incomes|with
considered|republicans|subj
considered|surplus|obj1
considered|overpayment|obj2
taxpayers|american|mod
overpayment|taxpayers|by
considered|and|punc
sought|primarily|mod-before
considered|sought|conj
sought|republicans|subj
sought|cut|mod
cut|republican|subj
cut|taxes|obj
cut|targeting|mod
targeting|$800 billion|obj
$800 billion|cuts|in
10|next|num-mod
years|10|amount-value
cuts|years|over
agree|they|subj
spending|more|mod
agree|spending|on
security|social|nn
spending|security|for
agree|instituting|mod
instituting|they|subj
benefit|prescription drug|nn
instituting|benefit|obj
benefit|medicare|for
medicare|and|punc
medicare|reduction|conj
debt|federal|mod
reduction|debt|of
debt|target|with
target|debt|of
debt|2016|by
