is|not|neg
is|enough|guest
housing|low-cost|mod
is|housing|pred
housing|united states|in
were|1995|in
earners|4.4 million|nn
low-income|more|mod
earners|low-income|mod
were|earners|pred
were|than|mod
than|were|comp1
units|low-cost|mod
units|housing|nn
were|units|pred
housing|affordable|mod
pool|housing|of
shrinking|pool|subj
dropping out|landlords|subj
dropping out|of|guest
dropping out|rent|of
programs|subsidy|nn
dropping out|programs|obj
programs|raise|rel
raise|program|subj
raise|rent|obj
raise|or|punc
raise|convert|conj
convert|program|subj
convert|real estate|obj
real estate|condominiums|to
number|homeless|of
rising|number|subj
going up|addition|in
going up|rents|subj
going up|faster|mod
faster|incomes|than
paying|1997|in
4.5 million|at least|num-mod
families|4.5 million|nn
paying|families|subj
paying|more|mod
more|50%|than
income|their|gen
50%|income|of
income|housing|on
paying|12%|up
12%|1991|since
address|crisis|obj
programs|various|mod
used|programs|obj
used|create|mod
create|program|subj
create|more|guest
housing|low-cost|mod
create|housing|obj
credits|tax|nn
created|credits|obj
created|encourage|mod
encourage|credit|subj
encourage|builders|obj
builders|build|rel
build|builder|subj
units|more|mod
build|units|obj
build|and|punc
build|build in|conj
build in|builder|subj
areas|low-income|mod
build in|areas|obj
made|grants|obj
organizations|non-profit|mod
made|organizations|to
organizations|build|rel
build|organization|subj
build|apartments|obj
elderly|and|punc
elderly|disabled|conj
jurisdiction|one|nn
granting|jurisdiction|subj
granting|builders|obj1
construction|greater|mod
construction|density|nn
granting|construction|obj2
construction|reserving|for
reserving|jurisdiction|subj
reserving|percentage|obj
percentage|units|of
units|rent|rel
rent|unit|subj
value|market|nn
rent|value|below
governments|local|nn
seize|governments|subj
houses|abandoned|mod
seize|houses|obj
houses|convert|rel
convert|house|subj
homes|affordable|mod
convert|homes|to
money|more|mod
allocated|money|obj
allocated|subsidize|mod
subsidize|money|subj
subsidize|landlords|obj
landlords|who|whn
rent|landlords|subj
value|market|nn
rent|value|below
trusts|estate|nn
trusts|investment|nn
were|formed|guest
specialized|that|subj
housing|affordable|mod
specialized|housing|in
money|more|mod
made|also|guest
made|money|obj1
made|available|desc
available|poor|to
vouchers|rent|mod
number|vouchers|of
vouchers|given|pnmod
dwellers|low-income|mod
dwellers|city|nn
given|dwellers|to
increased|number|obj
using|these|obj
vouchers|buy|rel
buy|voucher|subj
buy|home|obj
became|vouchers|subj
became|possible|desc
possible|2000|in
loans|special|mod
loans|low-interest|mod
were|made|pred
made|available|desc
available|low-income|to
low-income|and|punc
individuals|minority|nn
low-income|individuals|conj
limit|dollar|nn
insured|federally|mod
mortgages|insured|mod
limit|mortgages|of
raised|limit|obj
wage|minimum|nn
proposed|also|mod-before
raising|proposed|fc
proposed|wage|obj
