introduction|scheduled|mod
introduction|january 1999|nn
indicate|introduction|prior to
introduction|euro|of
indicate|polls|subj
citizens|european union|nn
indicate|are|fc
are|in|pred
are|favor|in
favor|it|of
are|and|punc
are|believe|conj
believe|citizens|subj
believe|be|fc
be|successful|pred
20%|only|mod
feel|20%|subj
informed|well|mod
feel|informed|desc
changes|upcoming|mod
informed|changes|about
maintains|european commission|subj
maintains|that|c
introduced|it|obj
introduced|schedule|on
supports|france|subj
supports|euro|obj
expects|zambia|subj
expects|benefit|fc
benefit|zambia|subj
benefit|it|from
begins|1996|by
development|euro|nn
development|design|nn
begins|development|subj
lenders|britain|gen
lenders|mortgage|nn
prepare for|lenders|subj
mortgages|euro|nn
prepare for|mortgages|obj
ascribed|1997|in
eur|code|nn
eur|"|punc
ascribed|"|punc
ascribed|eur|obj
ascribed|euro|to
companies|few german|nn
prepared for|companies|subj
prepared for|transition|obj
announces|1998|by
bundesbank|germany|gen
announces|bundesbank|subj
announces|that|c
investors|private|mod
benefit|investors|subj
benefit|it|from
