speaker|house newt gingrich|of
resigned|speaker|subj
resigned|from|guest
resigned|his|from
seat|house|nn
resigned|seat|obj
seat|effective|pnmod
filed for|july|in
filed for|he|subj
filed for|divorce|obj
marianne|his|gen
marianne|wife|nn
divorce|marianne|from
prompted|this|subj
prompted|series|obj
series|claims|of
claims|and|punc
claims|counterclaims|conj
each other|two|nn
each other|about|mod
assets|each other|gen
counterclaims|assets|between
assets|and|punc
affairs|personal|mod
assets|affairs|conj
gingrich|mrs.|title
served|gingrich|subj
served|notice|obj
notice|depose|rel
depose|notice|subj
depose|number|obj
husband|her|gen
friends|husband|gen
friends|close|mod
number|friends|of
friends|and|punc
friends|advisors|conj
advisors|and|punc
advisors|callista bisek|conj
aide|congressional|mod
having|whom|obj
having|he|subj
affair|years|for
bisek|ms.|title
filed|bisek|subj
filed|request|obj
request|overturn|rel
overturn|request|subj
overturn|requests|obj
requests|her|for
requests|answer|rel
answer|request|subj
answer|questions|obj
reached|gingriches|subj
reached|agreement|obj
agreement|dividing|on
dividing|gingriches|subj
assets|their|gen
dividing|assets|obj
assets|september|in
