bertand piccard|swiss|mod
bertand piccard|balloonist|nn
abandoned|bertand piccard|subj
attempt|his|gen
attempt|first|post
abandoned|attempt|obj
attempt|circumnavigate|rel
circumnavigate|attempt|subj
circumnavigate|world|obj
world|non-stop|pnmod
hours|balloon|nn
hours|six|amount-value
non-stop|hours|in
hours|take-off|after
leak|fuel|nn
take-off|leak|because of
leak|january 12 , 1997|appo
attempt|his|gen
attempt|second|post
departed|attempt|for
departed|piccard|subj
departed|switzerland|obj
departed|january 28 , 1998|mod
planned|he|subj
planned|drift|fc
drift|he|subj
drift|italy|toward
italy|greece|conj
greece|and|punc
greece|middle east|conj
middle east|and|punc
streams|ride|nn
streams|jet|nn
middle east|streams|conj
streams|east-bound|pnmod
east-bound|there|from
drift|completing|mod
completing|adventure|obj
days|10-20|amount-value
adventure|days|in
abandoned|piccard|subj
abandoned|attempt|obj
abandoned|when|wha
refused|china|subj
refused|him|obj1
refused|entry|obj2
refused|causing|mod
causing|china|subj
causing|him|obj
causing|miss|mod
winds|needed|mod
miss|winds|obj
attempt|his|gen
attempt|third|post
delayed|attempt|obj
delayed|by|by-subj
delayed|difficulties|by
difficulties|getting|rel
getting|difficulty|subj
permission|fly-over|nn
getting|permission|obj
permission|china|from
was|march 5 , 1999|on
was|sailing|pred
sahara desert|africa|gen
sailing|sahara desert|over
