earthquakes|two|nn
simultaneous|nearly|mod
earthquakes|simultaneous|mod
struck|measuring|mod-before
measuring|earthquake|subj
measuring|7.4|obj
7.4|richter scale|on
struck|earthquakes|subj
struck|in|guest
struck|izmit|in
southeast|region|nn
struck|southeast|obj
southeast|istanbul|of
istanbul|early|pnmod
early|morning|in
morning|17 august 1999|of
quakes|followed|vrel
followed|quakes|obj
followed|by|by-subj
aftershocks|27|num
followed|aftershocks|by
did|quakes|subj
damage|extensive|mod
did|damage|obj
indicate|reports|subj
damage|extensive|mod
indicate|damage|obj
deaths|10,000|num
deaths|45,000|num
10,000|trapped|pnmod
buildings|damaged|mod
trapped|buildings|in
buildings|and|punc
buildings|houses|conj
damaged|shocks|subj
damaged|bridges|obj
bridges|highways|appo
highways|power stations|appo
lines|telephone|nn
fire|large|mod
fire|izmit refinery|at
teams|foreign|mod
teams|rescue|nn
assisting|world|subj
providing|world|subj
providing|aid|obj
aid|and|punc
operations|rescue|nn
aid|operations|conj
account for|earthquake|subj
account for|$20 billion|obj
loss|economic|mod
$20 billion|loss|in
