government|myanmar|gen
reported|government|subj
500|over|num-mod
activists|500|nn
activists|anti-government|mod
reported|activists|obj
activists|surrendered|vrel
surrendered|activists|obj
surrendered|march 1999|in
far|so|mod
groups|17|num
made|groups|subj
made|peace|obj
october|early|mod
seized|october|in
men|armed|mod
seized|peacefully|mod-before
seized|men|subj
seized|myanmar embassy|obj
myanmar embassy|bangkok|in
release|demanding|mod
bangkok|release|conj
release|political prisoners|of
political prisoners|and|punc
political prisoners|recognition|conj
elections|1990|num
recognition|elections|of
suffers|thailand|subj
flow|cross-border|mod
suffers|flow|from
flow|narcotics|of
narcotics|hiv|conj
hiv|and|punc
hiv|refugees|conj
refugees|myanmar|from
stormed|2000|in
guerrillas|burmese|mod
stormed|guerrillas|subj
hospital|thai|mod
stormed|hospital|obj
hospital|january|in
agreed|us|subj
agreed|accept|fc
accept|the us|subj
refugees|1,500|num
refugees|burmese|mod
refugees|student|nn
accept|refugees|obj
refugees|thailand|from
denied|myanmar|obj1
certification|us|nn
certification|anti-drug|mod
denied|certification|obj2
trafficking|heroin|nn
certification|trafficking|for
awarded|suu kyi|obj1
awarded|dublin|obj2
dublin|ireland freedom|appo
honor|city|nn
ireland freedom|honor|of
activism|her|gen
activism|pro-democracy|mod
honor|activism|for
