world heritage bureau|unesco|gen
gave|world heritage bureau|subj
government|australian|mod
gave|government|obj
government|april 15 , 1999|until
april 15 , 1999|provide|rel
provide|april 15, 1999|subj
rebuttal|comprehensive|mod
provide|rebuttal|obj
report|its|gen
rebuttal|report|to
report|declaring|rel
declaring|report|subj
declaring|kakadu national park|obj
kakadu national park|endangered|vrel
endangered|kakadu national park|obj
endangered|by|by-subj
mine|jabiluka|nn
mine|uranium|nn
endangered|mine|by
allowed|government|subj
continue|work|subj
recommendation|unesco|gen
continue|recommendation|despite
recommendation|halted|comp1
halted|it|obj
rebuttal|australia|gen
cited|rebuttal|subj
cited|errors|obj
errors|science|of
science|law|conj
law|and|punc
law|logic|conj
logic|and|punc
unesco|declared|mod
findings|unesco|gen
logic|findings|conj
findings|inconsistent|pnmod
inconsistent|fact|with
fact|that|c
mine|nearby|mod
operated|mine|subj
years|20|amount-value
operated|years|for
impact|adverse|mod
years|impact|without
mine|jabiluka|nn
critics|mine|of
include|critics|subj
include|greens|obj
greens|and|punc
people|local|mod
people|mirrar aboriginal|nn
greens|people|conj
protestors|two|nn
protestors|aboriginal|mod
won|protestors|subj
won|1999|guest
won|goldman environmental prize|obj
goldman environmental prize|delayed|for
delayed|protestor|subj
goldman environmental prize|project|rel
project|goldman environmental prize|obj
project|mine|subj
