woman|richest|mod
richest|and|punc
influential|most|mod
richest|influential|conj
is|woman|pred
woman|entertainment|in
show|her|gen
show|tv|nn
show|talk|nn
continues|show|subj
success|its|gen
success|top|mod
success|ratings|nn
continues|success|obj
success|its|since
success|launching|rel
launching|success|subj
launching|september 1986|in
launching|winning|mod
emmys|32|num
emmys|daytime|mod
winning|emmys|obj
been|successful|pred
successful|promoting|in
promoting|she|subj
promoting|books|obj
authors|their|gen
having|authors|obj
show|her|gen
authors|show|on
having|and|punc
having|making|conj
movie|tv|nn
making|movie|obj1
making|versions|desc
versions|some|of
some|novels|of
presenting|she|subj
change|"|punc
presenting|change|obj
theme|your|gen
theme|life|nn
theme|"|punc
theme|focusing|rel
focusing|theme|subj
theme|and|punc
attitude|truth-will-set-you-free|mod
theme|attitude|conj
attitude|influenced|vrel
influenced|attitude|obj
influenced|by|by-subj
childhood|her own|gen
childhood|traumatic|mod
influenced|childhood|by
seminar|free|mod
seminar|over-the-tube|mod
given|seminar|obj1
given|by|by-subj
by|"|punc
given|change|by
john gray|your|gen
john gray|life|nn
john gray|"|punc
john gray|guru|nn
given|john gray|obj2
remains|she|subj
remains|proponent|obj
reading|inspirational|mod
proponent|reading|of
