magazine|oprah winfrey|gen
magazine|new|mod
magazine|"|punc
magazine|o|appo
scheduled|"|punc
scheduled|magazine|obj
scheduled|go|mod
go|magazine|subj
go|sale|on
go|april 2000|mod
accuses|lawsuit|subj
accuses|oprah|obj
pictures|her|in
claims|oprah|subj
claims|paid|fc
paid|she|subj
paid|photographers|obj
photographers|license|for
license|use|rel
use|license|subj
use|pictures|obj
use|anywhere|mod
anywhere|wants|rel
wants|anywhere|obj
wants|she|subj
says|counterclaim|subj
says|use|fc
use|she|subj
use|them|obj
packages|publicity|nn
use|packages|for
show|her|gen
show|talk|nn
packages|show|for
show|but|punc
show|not|punc
show|book|conj
movie|tv|nn
tuesdays|morrie|with
movie|best|mod
movie|tv|nn
honored|movie|as
jack lemmon|and|punc
hank azaria|co-star|nn
jack lemmon|hank azaria|conj
received|jack lemmon|subj
received|emmys|obj
roles|their|gen
emmys|roles|for
roles|movie|in
seeking|women|obj
votes|al gore|conj
al gore|and|punc
al gore|george bush|conj
appeared|votes|subj
appeared|separately|mod
show|oprah|gen
separately|show|on
