departing|switzerland|obj
switzerland|march 1 , 1999 ,|on
team|swiss/british|nn
team|balloon|nn
after|drifted|comp1
drifted|team|subj
southwestward|north africa|to
north africa|catching|before
stream|favorable|mod
stream|jet|nn
catching|stream|obj
degrees|9.27|amount-value
longitude|degrees|nn
longitude|west|nn
stream|longitude|at
flew|there|from
flew|team|subj
flew|east|obj
east|asia|across
east|then|pnmod
then|pacific|over
days|six|amount-value
pacific|days|for
days|mexico|to
mexico|leaving|nn
mexico|team|appo
team|floated|vrel
floated|team|obj
floated|central america|over
floated|crossed|conj
crossed|team|subj
crossed|caribbean|obj
caribbean|jamaica|towards
crossed|and|punc
crossed|steered|conj
steered|team|subj
finish line|"|punc
steered|finish line|towards
steered|"|punc
steered|somewhere|mod
west|longitude|nn
degrees|9.27|amount-value
west|degrees|nn
somewhere|west|along
west|mauritania|in
day|their|gen
day|18th|mod
day|began|rel
began|day|obj
began|balloonists|subj
began|crossing|mod
crossing|balloonist|subj
crossing|atlantic|obj
leg|last|post
atlantic|leg|on
flight|successful|mod
flight|non-stop|mod
flight|around-the-world|mod
flight|balloon|nn
be|flight|pred
