delays|piccard|conj
piccard|and|punc
piccard|british brian jones|conj
british brian jones|set|vrel
set|british brian jones|obj
set|off|mod
off|switzerland|from
switzerland|march 1 , 1999|on
drifted|they|subj
drifted|down|mod
down|north africa|to
drifted|and|punc
crossed|then|mod-before
drifted|crossed|conj
crossed|they|obj
crossed|asia|toward
gotten|permission|obj
departure|their|gen
permission|departure|before
passed over|they|subj
china|southern|mod
passed over|china|obj
stream|jet|nn
whisked|stream|subj
whisked|them|obj
whisked|pacific ocean|over
pacific ocean|grinding|before
grinding|stream|subj
halt|near|mod
grinding|halt|to
halt|central america|over
picked up|finally|mod-before
picked up|they|subj
stream|jet|nn
picked up|stream|obj
picked up|thursday|mod
beat|they|subj
record|endurance|nn
beat|record|obj
record|set|vrel
set|record|obj1
set|just|guest
weeks|two|amount-value
prior|weeks|nn
set|prior|obj2
elated|balloonists|obj
learning|balloonist|subj
learning|had|fc
had|they|subj
fuel|enough|mod
had|fuel|obj
fuel|reach|rel
reach|fuel|subj
reach|finish line|obj
degrees|9|amount-value
longitude|degrees|nn
finish line|longitude|appo
reach|africa|in
africa|midday|by
reach|saturday|mod
