problem|major|mod
is|problem|pred
problem|kenya|in
afflicted|1999|in
people|1.9 million|nn
afflicted|people|obj
has|nation|subj
has|national aids|obj
national aids|and|punc
program|sti|nn
national aids|program|conj
provided|world bank|subj
provided|$46 million|obj
$46 million|program|for
program|enhance|rel
enhance|program|subj
enhance|awareness|obj
awareness|scourge|of
fund|un children|gen
declared|fund|subj
declared|war|obj
war|aids|on
declared|and|punc
declared|urged|conj
urged|fund|subj
join|churches|subj
sought|money|obj
sought|treatment|for
treatment|and|punc
initiatives|education|nn
treatment|initiatives|conj
dispensers|free|mod
dispensers|condom|nn
installed|dispensers|obj
areas|public|mod
installed|areas|in
was|2000|in
policy|public|mod
was|reviewed|pred
reviewed|address|mod
address|policy|subj
problems|housing|nn
problems|and|punc
problems|"|punc
problems|loopholes|conj
loopholes|"|punc
loopholes|that|whn
encouraged|loopholes|subj
encouraged|spread|obj
spread|disease|of
is|also|amod
problem|major|mod
problem|health|nn
is|problem|pred
cases|3 million|nn
problem|cases|with
cases|africa|in
is|year|mod
was|helping|pred
helping|fight|with
campaigns|anti-malaria|mod
are|run|pred
distributed|drugs|obj
bringing in|kenya|subj
drugs|sulphur-based|mod
bringing in|drugs|obj
bringing in|since|mod
strains|parasite|of
since|were|comp1
were|chloroquin|pred
water|other|mod
borne|water|subj
include|diseases|subj
include|typhoid|obj
typhoid|cholera|conj
cholera|dysentery|conj
dysentery|and|punc
fever|hemorrhagic|mod
dysentery|fever|conj
boil|kenyans|subj
water|their|gen
boil|water|obj
providing|japan international agency|subj
providing|money|obj
money|research|for
research|and|punc
research|control|conj
control|infectious diseases|of
able|less|mod
is|able|pred
is|fight|mod
fight|population|subj
fight|diseases|obj
diseases|malnutrition|because of
eight percent|children|of
die|eight percent|subj
die|age|by
age|5|num
age|malnutrition|because of
kenya|and|punc
food and agriculture organization|un|nn
kenya|food and agriculture organization|conj
sponsored|kenya|subj
sponsored|workshop|obj
workshop|1999|in
increased|greatly|amod
increased|nation|subj
increased|number|obj
specialists|heart|nn
number|specialists|of
specialists|who|whn
treat|specialists|subj
disease|coronary artery|nn
treat|disease|obj
disease|which|whn
afflicting|disease|subj
affluent|more|mod
afflicting|affluent|obj
disease|rheumatic|mod
disease|heart|nn
disease|poor|in
defects|congenital|mod
clothing|used|mod
prevent|safe|subj
diseases|fungal|mod
prevent|diseases|obj
