activity|criminal|mod
activity|china|in
china|ways|in
is|similar|pred
similar|crimes|to
crimes|committed|vrel
committed|crimes|obj
countries|other|mod
committed|countries|in
activities|usual|mod
activities|criminal|mod
are|activities|pred
activities|armed robbery|of
armed robbery|murder|appo
crimes|drug-related|mod
firearms|illegal|mod
crimes|firearms|appo
appears|china|subj
be|most|pred
most|concerned|pnmod
crimes|gang-related|mod
concerned|crimes|regarding
wealthy persons|kidnapping|nn
crimes|wealthy persons|conj
wealthy persons|ransom|for
ransom|and|punc
ransom|hooliganism|conj
fighting|china|nn
fighting|crime|nn
complicated|fighting|obj
complicated|by|by-subj
crime|cross-border|mod
complicated|crime|by
crime|macau|from
macau|and|punc
macau|hong kong|conj
jurisdictions|two|nn
control|chinese|nn
come|control|under
police|macau|in
arrested|police|subj
member|three|nn
arrested|member|obj
gang|"|punc
gang|14k|nn
gang|triad|nn
gang|"|punc
member|gang|of
gang|who|whn
are|close|pred
leader|gang|nn
close|leader|to
kuok-koi|wan|mod
leader|kuok-koi|appo
tat-hou|wong|nn
are|tat-hou|pred
wan-wa|wong|nn
tat-hou|wan-wa|conj
wan-wa|and|punc
iok-im|lam|nn
wan-wa|iok-im|conj
activity|gang|gen
activity|criminal|mod
caused|activity|subj
caused|china|obj
china|want|rel
want|china|subj
want|authorities|obj
authorities|macau|in
macau|clamp down|rel
clamp down|macau|subj
clamp down|harder|mod
activities|criminal|mod
harder|activities|on
members|gang|of
gang|established|vrel
established|gang|obj
established|by|by-subj
established|zeng qiqiang|by
arrested|members|obj
arrested|involvement|for
30|more than|num-mod
cases|30|nn
involvement|cases|in
cases|blackmail|of
blackmail|gambling|conj
use|illegal|mod
gambling|use|conj
use|guns|of
guns|and|punc
crimes|other|mod
guns|crimes|conj
gambling|south china|in
arrested|police|subj
tza-keung|cheung|nn
arrested|tza-keung|obj
tza-keung|and|punc
tza-keung|members|conj
gang|his|gen
members|gang|of
gang|who|whn
worked out|gang|subj
worked out|china|of
crimes|gang|gen
committed|mostly|amod
committed|crimes|obj
committed|hong kong|in
tried|subsequently|amod
tried|cheung|obj
tried|china|in
intensified|china|subj
activity|its|gen
activity|anti-crime|mod
intensified|activity|obj
program|"|punc
program|strike-hard|nn
program|"|punc
activity|program|through
signed|also|amod
signed|nation|subj
agreements|legal|mod
agreements|assistance|nn
signed|agreements|obj
countries|28|num
agreements|countries|with
countries|and|punc
treaties|extradition|nn
countries|treaties|conj
countries|ten|nn
treaties|countries|with
