activity|criminal|mod
activity|china|in
rising|activity|subj
rising|especially|mod
murder|robbery|conj
robbery|bombings|conj
bombings|theft|conj
activity|gang|nn
theft|activity|conj
activity|juvenile delinquency|conj
juvenile delinquency|and|punc
felonies|migrant|mod
juvenile delinquency|felonies|conj
prostitution|gambling|conj
gambling|and|punc
problems|drug|nn
gambling|problems|conj
persist|prostitution|subj
corruption|and|punc
corruption|bribery|conj
widespread|still|mod
is|widespread|pred
sixty percent|criminals|of
are|minors|pred
launched|april 1996|in
police|chinese|nn
launched|police|subj
crackdown|nationwide|mod
launched|crackdown|obj
crime|serious|mod
crackdown|crime|on
crime|emphasis|with
crimes|gang-related|mod
emphasis|crimes|on
crimes|those|conj
those|involving|rel
involving|those|subj
involving|guns|obj
guns|and|punc
manufacture|gun|nn
guns|manufacture|conj
crackdown|and|punc
crackdown|smuggling|conj
smashed|gangs|obj
made|arrests|subj
sentenced|criminals|obj
sentenced|death|to
death|or|punc
death|life|conj
life|prison|in
robber|bank|nn
robber|and|punc
liao yanxiong|killer|nn
robber|liao yanxiong|conj
executed|robber|obj
property|cash|conj
cash|guns|conj
guns|ammunition|conj
tools|gun-making|mod
ammunition|tools|conj
tools|explosives|conj
explosives|and|punc
explosives|vehicles|conj
seized|property|obj
aided|often|amod
aided|police|obj
aided|by|by-subj
aided|tips|by
tips|citizens|from
passed|china|subj
laws|new|mod
passed|laws|obj
laws|strengthen|rel
strengthen|law|subj
rights|human|nn
strengthen|rights|obj
strengthen|and|punc
strengthen|amended|conj
amended|law|subj
laws|criminal|nn
amended|laws|obj
laws|enhance|rel
enhance|law|subj
enhance|fight|obj
fight|organized crime|against
organized crime|money-laundering|conj
money-laundering|terrorism|conj
terrorism|trafficking|conj
immigrants|illegal|mod
trafficking|immigrants|in
immigrants|and|punc
crime|environment-related|mod
immigrants|crime|conj
plans|china|subj
plans|crack down on|fc
crack down on|china|subj
crack down on|corruption|obj
corruption|smuggling|conj
smuggling|and|punc
crimes|other|mod
crimes|economic|mod
smuggling|crimes|conj
wants|china|subj
wants|strengthen|fc
strengthen|china|subj
cooperation|international|mod
strengthen|cooperation|obj
cooperation|fighting|in
fighting|crime|obj
signed|it|subj
agreements|judicial|mod
agreements|assistance|nn
signed|agreements|obj
countries|28|num
agreements|countries|with
countries|and|punc
agreements|extradition|nn
countries|agreements|conj
agreements|ten|with
chinese|and|punc
police|hong kong|nn
chinese|police|conj
crushed|jointly|mod-before
crushed|chinese|subj
gang|cross-border|mod
crushed|gang|obj
gang|led|vrel
led|gang|obj
led|by|by-subj
tza-keung|cheung|nn
led|tza-keung|by
tza-keung|(|punc
tza-keung|spender|appo
spender|)|punc
spender|which|whn
kidnapped|spender|subj
members|tycoons|gen
members|family|nn
kidnapped|members|obj
ransom|$205 million|nn
members|ransom|for
crimes|other|mod
kidnapped|crimes|among
incriminated|cheung|subj
chi-ho|his|gen
chi-ho|henchman|nn
chi-ho|chan|nn
incriminated|chi-ho|obj
crushed|china|subj
gang|mainland|nn
crushed|gang|obj
gang|related|vrel
related|gang|obj
gang|larger|mod
gang|macao|nn
related|gang|to
gang|and|punc
cooperation|pledged|mod
cooperation|increased|mod
cooperation|anti-crime|mod
gang|cooperation|conj
cooperation|macao|with
urged|it|subj
get|portugal|subj
get|tougher|desc
crime|macao|nn
tougher|crime|on
return|colony|gen
crime|return|before
return|china|to
china|1999|in
station|china|subj
station|troops|obj
station|there|mod
station|and|punc
station|deal|conj
deal|china|subj
deal|more|obj
deal|harshly|mod
harshly|criminals|with
