phenomenon|periodic|mod
phenomenon|weather|mod
is|phenomenon|pred
warming|water|of
pacific|eastern|mod
water|pacific|in
changes|winds|obj
winds|and|punc
winds|atmospheric pressure|conj
changes|shifting|mod
patterns|weather|mod
shifting|patterns|obj
shifting|and|punc
shifting|reducing|conj
release|carbon dioxide|nn
reducing|release|obj
cause|it|subj
cause|storms|obj
storms|california|in
california|tornadoes|appo
tornadoes|florida|in
winter|mild|mod
cause|winter|mod
states|northern|mod
winter|states|in
cause|and|punc
cause|reduce|conj
reduce|it|subj
reduce|number|obj
hurricanes|atlantic|nn
number|hurricanes|of
cause|also|mod-before
cause|it|subj
cause|storms|obj
flooding|south america|in
south america|and|punc
south america|africa|conj
south america|droughts|appo
droughts|indonesia|in
flooding|and|punc
flooding|flooding|conj
flooding|china|in
water|increased|mod
borne|water|subj
borne|illnesses|obj
illnesses|africa|in
production|decreased|mod
production|milk|mod
production|california|in
attributed|also|guest
attributed|production|obj
attributed|el ninos|to
condition|opposite|mod
is|condition|pred
is|abnormal|pred
is|cooling|mod
cooling|of|guest
sea|pacific|nn
cooling|sea|of
cooling|surface|obj
surface|creating|rel
creating|surface|subj
stream|colder|mod
stream|stronger|mod
stream|jet|nn
creating|stream|obj
atmosphere|upper|mod
stream|atmosphere|in
is|la nina|during
is|wet|pred
wet|and|punc
wet|cold|conj
dry|exceptionally|mod
is|dry|pred
warm|abnormally|mod
is|warm|pred
tornados|more|mod
are|tornados|pred
tornados|and|punc
tornados|thunderstorms|conj
thunderstorms|mid-west|in
mid-west|and|punc
hurricanes|more|mod
mid-west|hurricanes|conj
hurricanes|atlantic|in
is|wet|pred
is|while|mod
part|southern|mod
part|continent|of
while|is|comp1
is|dry|pred
scientists|world|around
trying|scientists|subj
trying|understand|fc
understand|scientist|subj
understand|track|conj
track|scientist|subj
track|and|punc
track|predict|conj
predict|scientist|subj
predict|phenomena|obj
satellites|nasa|nn
measure|satellites|subj
temperatures|sea|mod
temperatures|surface|mod
measure|temperatures|obj
system|el nino|nn
system|detection|nn
consists of|system|subj
stations|70|num
stations|buoy-borne|mod
consists of|stations|obj
stations|monitoring|rel
monitoring|station|subj
winds|pacific|nn
monitoring|winds|obj
winds|and|punc
winds|waves|conj
scientists|united states|in
united states|australia|conj
australia|israel|conj
israel|and|punc
israel|germany|conj
using|scientists|subj
simulations|sophisticated|mod
simulations|computer|nn
using|simulations|obj
seeking|chinese|subj
seeking|links|obj
links|el nino|between
el nino|and|punc
cycles|sunspot|nn
el nino|cycles|conj
cylinder|30-foot-long|mod
cylinder|mud|of
american|south|nn
mud|american|from
is|analyzed|pred
analyzed|track|mod
cycles|weather|mod
track|cycles|obj
track|back|mod
years|15,000|num
track|years|mod
