speaker|house|of
house|newt gingrich|appo
resigned|speaker|subj
resigned|from|guest
resigned|his|from
seat|house|nn
resigned|seat|obj
seat|january 6 , 1999|on
filed for|july 1999|in
filed for|he|subj
filed for|divorce|obj
filed for|prompting|mod
prompting|he|subj
prompting|series|obj
series|claims|of
claims|and|punc
claims|counterclaims|conj
counterclaims|him|between
him|and|punc
wife|his|gen
him|wife|conj
affairs|personal|mod
wife|affairs|over
affairs|and|punc
affairs|assets|conj
gingrich|mrs.|title
served|also|mod-before
served|gingrich|subj
served|notice|obj1
notice|depose|rel
depose|notice|subj
depose|callista bisek|obj
gingrich|mr.|title
having|notice|obj
having|gingrich|subj
served|affair|obj2
affair|years|for
reached|september 1999|in
reached|gingriches|subj
reached|agreement|obj
agreement|dividing|on
dividing|gingriches|subj
assets|their|gen
dividing|assets|obj
gingrich|mrs.|title
filed|gingrich|subj
filed|requests|obj
requests|depose|rel
depose|request|subj
depose|several|obj
husband|her|gen
friends|husband|gen
friends|close|mod
several|friends|of
friends|and|punc
friends|advisers|conj
bisek|ms.|title
filed|bisek|subj
filed|request|obj
request|overturn|rel
overturn|request|subj
overturn|requirement|obj
requirement|her|for
requirement|answer|rel
answer|requirement|subj
answer|questions|obj
