took off|january 12 , 1997 ,|on
team|swiss/belgian|nn
took off|team|subj
took off|swiss alps|from
swiss alps|bid|in
bid|balloon|comp1
balloon|team|subj
balloon|non-stop|mod
non-stop|world|around
expecting|travel|fc
two|about|num-mod
weeks|two|amount-value
travel|weeks|for
men|two|nn
aborted|men|subj
hours|their|gen
hours|attempt|nn
hours|six|amount-value
aborted|hours|obj
hours|takeoff|after
leak|hazardous|mod
leak|fuel|nn
takeoff|leak|due to
resumed|(|punc
resumed|now|mod-before
including|also|amod
now|including|rel
including|now|subj
including|englishman|obj
resumed|)|punc
resumed|team|subj
resumed|quest|obj
resumed|but|punc
resumed|had|conj
had|team|obj
had|abandon|mod
abandon|team|subj
journey|their|gen
abandon|journey|obj
abandon|as|mod
as|refused|comp1
refused|china|subj
refused|them|obj1
refused|entry|obj2
airspace|its|gen
entry|airspace|into
december|late|mod
team|revamped|mod
team|swiss/british|nn
prepared for|with|mod-before
permission|conditional|mod
prepared for|permission|with
permission|china|from
china|fly over|rel
fly over|china|subj
terrain|its|gen
fly over|terrain|obj
prepared for|team|subj
attempt|third|post
prepared for|attempt|obj
attempt|feat|at
