18|promising|mod
son|year-old|mod
parents|jamaican|mod
parents|immigrant|nn
son|parents|of
stabbed|death|to
stop|london|nn
stop|bus|nn
death|stop|at
stop|april 1993|in
attacked|he|obj
attacked|by|by-subj
youths|five|nn
youths|white|mod
attacked|youths|by
youths|history|with
baiting|race|nn
history|baiting|of
killers|alleged|mod
three|killers|of
tried|three|obj
two|other|num-mod
charges|two|against
dropped|charges|obj
evidence|insufficient|mod
dropped|evidence|for
racism|police|nn
believed|racism|obj
believed|led to|mod
led to|racism|subj
handling|poor|mod
led to|handling|obj
handling|case|of
case|five|against
metropolitan police|london|gen
government|later|mod
found|government|according to
found|report|obj
riven|"|punc
found|riven|mod
racism|pernicious|mod
pernicious|and|punc
pernicious|institutionalized|conj
riven|racism|with
before|even|mod
issued|report|obj
confidence|public|mod
confidence|police|in
fallen|confidence|subj
murder|lawrence|nn
murder|and|punc
aftermath|its|gen
murder|aftermath|conj
served|murder|subj
served|question|mod
question|murder|subj
belief|common|mod
question|belief|obj
belief|britain|in
relations|its|gen
relations|race|nn
are|better|pred
are|than|mod
than|are|comp1
are|in|pred
are|united states|in
overall|britain|nn
white|94%|nn
is|white|pred
is|and|punc
had|never|amod
is|had|conj
had|overall|subj
movement|civil rights|nn
had|movement|obj
is|london|in
20%|population|of
is|minority|pred
is|but|punc
is|are|conj
2.3%|only|mod
are|2.3%|pred
force|police|nn
2.3%|force|of
government|labor|nn
government|tony blair|of
promised|government|subj
overhaul|radical|mod
promised|overhaul|obj1
overhaul|race|of
laws|discrimination|nn
promised|laws|obj2
promised|and|punc
promised|hoped|conj
hoped|government|subj
hoped|that|c
years|ten|amount-value
reflect|years|in
force|police|nn
force|england|in
england|and|punc
england|wales|conj
reflect|force|subj
make-up|racial|mod
reflect|make-up|obj
make-up|area|of
area|served|rel
served|area|obj
served|it|subj
years|seven|amount-value
murder|lawrence|nn
years|murder|after
cracking down on|police|subj
crime|racist|mod
cracking down on|crime|obj
crime|london|in
london|operation|under
operation|named|vrel
named|operation|obj1
named|athena|obj2
launched|2000|in
charles|price|nn
launched|charles|subj
launched|scholarship|obj
scholarship|memory|in
memory|lawrence|of
lawrence|open|rel
open|lawrence|subj
open|up|guest
open|architecture|obj
field of study|lawrence|gen
field of study|chosen|mod
architecture|field of study|appo
minorities|ethnic|mod
open|minorities|to
expressed|also|mod-before
expressed|prince|subj
sympathy|his|gen
sympathy|deepest|mod
expressed|sympathy|obj
parents|stephen|gen
sympathy|parents|to
