executed|five|during
five|and|punc
five|half|conj
half|years|guest
tenure|george w. bush|gen
half|tenure|of
tenure|governor|as
executed|texas|subj
prisoners|143|num
executed|prisoners|obj
row|death|nn
prisoners|row|on
more|far|mod
row|more|pnmod
state|other|mod
more|state|than
state|modern times|during
women|juveniles|appo
deficient|mentally|mod
were|among|pred
were|those|among
said|repeatedly|amod
said|bush|subj
said|that|c
reviews|he|subj
reviews|case|obj
reviews|for|mod
doubt|condemned|of
for|'s|comp1
's|guilt|pred
one|only|mod
has|one|in
has|case|subj
has|bush|obj
bush|granted|vrel
granted|bush|obj1
reprieve|30-day|nn
granted|reprieve|obj2
granted|and|punc
granted|told|conj
told|bush|subj
board|parole|nn
told|board|obj
board|review|rel
review|board|subj
review|case|obj
review|so|mod
tests|dna|nn
so|pursued|comp1
pursued|tests|obj
halt|law|by
governor|texas|nn
halt|governor|subj
halt|execution|obj
texas board of pardons|and|punc
texas board of pardons|paroles|conj
recommends|first|subj
recommends|reprieve|obj
reprieve|commutation|conj
sentence|life|nn
commutation|sentence|to
sentence|or|punc
sentence|pardon|conj
veto|he|subj
vote|board|nn
veto|vote|obj
vote|recommendations|on
overrule|he|subj
vote|board|nn
overrule|vote|obj
vote|proceed|rel
proceed|vote|subj
proceed|execution|with
appointed|board|obj
appointed|by|by-subj
appointed|governor|by
governor|bush|person
appointed|and|punc
appointed|believed|conj
believed|board|obj
believed|share|mod
share|board|subj
views|his|gen
share|views|obj
punishment|capital|nn
views|punishment|on
governor|bush|person
vetoed|governor|subj
vetoed|bill|obj
bill|establish|rel
establish|bill|subj
system|state|nn
system|public defender|nn
establish|system|obj
system|such|pre
lacking|system|obj
defendants|indigent|mod
defended|poorly|amod
defended|defendants|obj
defended|study|according to
study|published|vrel
published|study|obj
tribune|chicago|nn
published|tribune|in
responded|bush|subj
responded|that|c
had|defendants|subj
access|full|mod
had|access|obj
trial|fair|mod
access|trial|to
claims|amnesty international|subj
process|texas|gen
process|secretive|mod
process|clemency|nn
criminals|condemned|mod
process|criminals|for
claims|violates|fc
violates|process|subj
safeguards|minimum|mod
violates|safeguards|obj
rights|human|nn
safeguards|rights|for
minister|canadian|mod
contended|minister|subj
contended|that|c
sentencing|foreign minister|subj
sentencing|canadian|obj
canadian|death|to
violated|row|subj
treaty|international|mod
violated|treaty|obj
sentence|death|nn
sentence|karla faye tucker|of
brought|sentence|subj
brought|pleas|obj
pleas|clemency|for
clemency|pope john paul ii|from
from|and|punc
from|from|conj
pat robertson|christian|nn
pat robertson|broadcaster|nn
from|pat robertson|from
conversion|tucker|gen
conversion|death|nn
conversion|row|nn
pat robertson|conversion|because of
conversion|christianity|to
