principle|fundamental|nn
foreign policy|mongolia|gen
principle|foreign policy|of
is|according to|mod-before
is|minister|according to
minister|external relations|of
is|that|c
be|active|pred
activities|political|mod
political|and|punc
political|economic|conj
active|activities|in
asia|northeast|mod
activities|asia|in
asia|and|punc
region|whole|mod
region|asian-pacific|nn
asia|region|conj
relationship|mongolia|gen
china|bordering|mod
china|neighbors|nn
relationship|china|with
china|and|punc
china|russia|conj
maintained|relationship|obj
level|appropriate|mod
maintained|level|at
relations|sino-mongolian|nn
normalized|relations|obj
normalized|1989|in
countries|two|nn
since|worked|comp1
worked|countries|subj
worked|strengthen|mod
strengthen|country|subj
strengthen|ties|obj
strengthen|and|punc
strengthen|develop|conj
develop|country|subj
cooperation|economic|mod
economic|and|punc
economic|trade|conj
develop|cooperation|obj
cooperation|interest|in
peace|regional|mod
interest|peace|of
peace|and|punc
peace|stability|conj
supports|china|subj
supports|mongolia|obj
zone|nuclear-free|mod
mongolia|zone|as
pledges|china|nn
pledges|abide|rel
abide|pledge|subj
abide|principles|by
co-existence|peaceful|mod
principles|co-existence|of
co-existence|and|punc
co-existence|treaty|conj
friendship|sino-mongolian|nn
treaty|friendship|on
friendship|and|punc
friendship|cooperation|conj
stated|russia|subj
stated|that|c
problems|economic|mod
economic|and|punc
economic|trade|conj
problems|russia|between
russia|and|punc
russia|mongolia|conj
resolved|problems|obj
conflicts|major|mod
are|conflicts|pred
countries|two|nn
conflicts|countries|between
is|in|pred
is|process|in
process|transforming|of
transforming|mongolia|subj
economy|central-planning|mod
transforming|economy|from
oriented-economy|market|nn
economy|oriented-economy|to
is|and|punc
is|requires|conj
requires|mongolia|subj
aid|technical|mod
technical|and|punc
technical|monetary|conj
aid|restructuring|for
for|and|punc
for|to|conj
for|help|to
improve|aid|subj
conditions|living|mod
improve|conditions|obj
conditions|country|of
ranks|mongolia|subj
ranks|among|guest
most|five|nn
ranks|most|among
countries|foreign|mod
countries|assisted|mod
ranks|countries|obj
countries|world|of
provider|main|mod
is|provider|pred
provider|aid|of
aid|mongolia|to
comes from|also|mod-before
comes from|aid|subj
comes from|us|obj
us|china|conj
britain|european countries|nn
britain|(|punc
china|britain|conj
britain|france|conj
france|denmark|conj
denmark|and|punc
canada|germany|nn
canada|)|punc
denmark|canada|conj
world bank|united nations|conj
united nations|and|punc
united nations|asian development bank|conj
decided|mongolia|subj
decided|apply|fc
apply|mongolia|subj
apply|join|mod
join|world trade organization|obj
world trade organization|and|punc
forum|asia-pacific economic cooperation|nn
world trade organization|forum|conj
