ocd|(|punc
obsessive-compulsive disorder|ocd|abbrev
ocd|)|punc
characterized|obsessive-compulsive disorder|obj
characterized|by|by-subj
thoughts|senseless|mod
thoughts|repetitive|mod
characterized|thoughts|by
thoughts|and|punc
thoughts|behaviors|conj
behaviors|which|whn
deal with|typically|mod-before
deal with|behaviors|subj
deal with|grooming|obj
grooming|contamination|conj
contamination|or|punc
contamination|danger|conj
wash|sufferers|subj
hands|their|gen
wash|hands|obj
wash|continually|mod
wash|or|punc
check|repeatedly|amod
wash|check|conj
check|sufferers|subj
appearance|their|gen
check|appearance|obj
appearance|mirrors|in
are|nervous|pred
are|and|punc
fidget|frequently|mod-before
are|fidget|conj
fidget|they|subj
fidget|and|punc
fidget|twitch|conj
twitch|they|subj
manual|diagnostic|mod
sufferers|american psychiatric association|nn
sufferers|states|nn
manual|sufferers|of
preoccupied|manual|obj
preoccupied|details|with
details|rules|conj
rules|order|conj
order|or|punc
order|schedules|conj
schedules|extent|to
extent|that|c
point|activity|of
is|lost|pred
show|they|subj
show|perfectionism|obj
perfectionism|that|whn
interferes|perfectionism|subj
completion|task|nn
interferes|completion|with
are|over-conscientious|pred
devoted|they|obj
devoted|work|to
work|and|punc
work|productivity|conj
productivity|exclusion|to
activities|leisure|mod
exclusion|activities|of
activities|and|punc
activities|friendships|conj
be|unable|pred
unable|discard|fc
discard|they|subj
objects|worthless|mod
discard|objects|obj
is|one|pred
group|related|mod
one|group|of
group|anxiety disorders|of
illnesses|other|mod
illnesses|group|in
include|illnesses|subj
attacks|panic|nn
include|attacks|obj
stress|post-traumatic|mod
attacks|stress|conj
stress|generalized anxiety disorders|conj
generalized anxiety disorders|phobias|conj
hoarding|animal|mod
phobias|hoarding|conj
hoarding|and|punc
disorder|body|nn
disorder|dysmorphic|mod
hoarding|disorder|conj
victims|ocd|nn
suffer|also|amod
suffer|victims|subj
suffer|anorexia|from
anorexia|and|punc
anorexia|depression|conj
is|evidence|pred
evidence|that|c
stem from|along with|mod-before
stem from|tinnitus|along with
tinnitus|and|punc
tinnitus|parkinson 's disease|conj
stem from|disorders|subj
defect--|same|post
defect--|brain|nn
stem from|defect--|obj
regions|two|nn
regions|brain|nn
decoupling|regions|of
regions|that|whn
work|normally|mod-before
work|regions|subj
work|synchrony|in
implanting|electrodes|obj
provide|relief|obj
consists of|treatment|subj
consists of|medications|obj
medications|psychotherapy|conj
psychotherapy|or|punc
psychotherapy|combination|conj
combination|two|of
drugs|effective|mod
include|drugs|subj
inhibitors|serotonin|nn
inhibitors|reuptake|nn
include|inhibitors|obj
prozac|flouxetine|nn
prozac|(|punc
inhibitors|prozac|such as
prozac|)|punc
zoloft|sertarline|nn
zoloft|(|punc
prozac|zoloft|conj
zoloft|)|punc
anafranil|clomipramine|nn
anafranil|(|punc
zoloft|anafranil|conj
anafranil|)|punc
anafranil|and|punc
luvox|fluvoxamine|nn
luvox|(|punc
anafranil|luvox|conj
has|each|subj
effectiveness|varying|mod
has|effectiveness|obj
effectiveness|and|punc
effects|side|nn
effectiveness|effects|conj
are|effective|pred
effective|children|with
children|who|whn
have|children|subj
have|ocd|obj
successful|most|mod
psychotherapy|successful|mod
appears|psychotherapy|subj
therapy|cognitive-behavioral|mod
be|therapy|pred
therapy|where|wha
learns|patient|subj
learns|moderate|mod
moderate|patient|subj
moderate|moods|obj
moods|manipulating|by
thoughts|his|gen
manipulating|thoughts|obj
direction|certain|mod
thoughts|direction|in
