was|born|pred
born|st. petersburg|in
st. petersburg|1952|in
graduated|he|subj
graduated|leningrad state university|from
graduated|and|punc
graduated|began|conj
began|he|subj
began|career|obj
career|spy|as
spy|kgb|with
years|15|amount-value
serving|years|obj
years|many|appo
many|those|of
those|germany|in
after|returned to|comp1
returned to|putin|subj
returned to|st. petersburg|obj
returned to|and|punc
returned to|began|conj
began|putin|subj
began|working|fc
working|putin|subj
government|local|nn
working|government|for
was|aide|pred
aide|mayor|to
was|from 1991 to 1996|mod
moved|then|mod-before
moved|he|subj
wife|his|gen
moved|wife|with
wife|and|punc
daughters|two|nn
wife|daughters|conj
daughters|moscow|to
moved|later|mod
moved|becoming|mod
becoming|he|subj
becoming|director|obj
director|federal security service|of
named|august 1999|in
named|boris yeltsin|subj
named|putin|obj1
prime minister|acting|mod
named|prime minister|obj2
named|and|punc
named|announced|conj
announced|boris yeltsin|subj
announced|that|c
wanted|he|subj
wanted|putin|obj
putin|succeed|rel
succeed|putin|subj
succeed|him|obj
succeed|president|as
president|election|in
election|scheduled|pnmod
scheduled|summer|for
summer|2000|of
suddenly|end|at
end|december|of
resigned|yeltsin|subj
resigned|and|punc
resigned|named|conj
named|yeltsin|subj
named|putin|obj1
president|acting|mod
named|president|obj2
moved|resignation|subj
moved|election|obj
election|march 2000|to
ran|putin|subj
campaign|slick|mod
ran|campaign|obj
ran|reaching out|mod
reaching out|putin|subj
groups|various|mod
groups|interest|nn
reaching out|groups|to
reaching out|raising|conj
raising|putin|subj
raising|pensions|obj
raising|and|punc
raising|promising|conj
promising|putin|subj
promising|raise|fc
raise|wages|obj
raise|improve|conj
improve|education|obj
improve|increase|conj
spending|conventional|mod
spending|defense|nn
increase|spending|obj
increase|and|punc
increase|fight|conj
fight|crime|obj
was|popular|pred
popular|many|with
stand|his|gen
stand|tough|mod
many|stand|because of
stand|war|in
war|chechnya|in
weeks|two|amount-value
weeks|election|before
book|interviews|of
published|book|obj
()|humanizing|at
image|his|gen
humanizing|image|obj
opponent|his|gen
opponent|main|mod
was|chief|pred
chief|communist party|of
won|putin|subj
election|march 26|nn
won|election|obj
election|53%|with
53%|vote|of
election|his|gen
moved|election|after
moved|he|subj
moved|very|mod
moved|cautiously|mod
did|not|neg
reveal|he|subj
plan|his|gen
plan|economic|mod
reveal|plan|obj
reveal|staying|mod
staying|he|subj
vague|intentionally|mod
staying|vague|desc
replace|also|mod-before
did|not|neg
replace|he|subj
replace|minister|obj
minister|defense|of
traveled|he|subj
traveled|only|mod
only|belarus|to
belarus|ukraine|conj
ukraine|and|punc
ukraine|united kingdom|conj
sworn in|he|obj
sworn in|may 5.|on
