stars wars episode i--the phantom menace|"|punc
began|mania|subj
began|1997|in
began|-release|with
-release|star wars trilogy|of
trailer|first|post
phantom menace|"|punc
trailer|phantom menace|of
screened|"|punc
screened|trailer|obj
screened|november 1989|in
screened|becoming|mod
becoming|trailer|subj
event|unprecedented|mod
event|film|nn
becoming|event|obj
trailer|movie|gen
trailer|second|post
went|trailer|subj
went|online|desc
online|march 1999|in
downloads|one million|nn
went|downloads|with
day|one|amount-value
downloads|day|in
had|internet|subj
had|hundreds|obj
sites|star|nn
sites|wars-related|mod
hundreds|sites|of
hasbro inc.|galoob toys , inc.|conj
galoob toys , inc.|and|punc
galoob toys , inc.|lego|conj
manufacturing|hasbro inc.|subj
manufacturing|goods|obj
goods|including|rel
including|goods|subj
clock|countdown|nn
including|clock|obj
release|may 17|nn
clock|release|for
bell|taco|nn
pepsi|bell|conj
bell|pizza hut|conj
pizza hut|kentucky fried chicken|conj
kentucky fried chicken|and|punc
promotions|pez candy dispensers|nn
promotions|planned|mod
kentucky fried chicken|promotions|conj
from|"|punc
minutes|60|amount-value
media--|minutes|from
minutes|"|punc
minutes|new york times|to
new york times|vogue--|to
running|media--|subj
running|features|obj
running|and|punc
running|creating|conj
creating|media--|subj
packages|press|nn
creating|packages|obj
attended|april 30 , 40,000|on
attended|fans|subj
star wars celebration|lucasfilmltd-sanctioned|nn
star wars celebration|"|punc
attended|star wars celebration|obj
star wars celebration|"|punc
star wars celebration|denver|in
had|stores|subj
hours|special|mod
had|hours|obj
hours|accommodate|rel
accommodate|hour|subj
accommodate|release|obj
release|merchandise|of
merchandise|may 2.|on
had|wal-mart|subj
goods|star|nn
goods|wars-related|mod
had|goods|obj
goods|16|in
departments|its|gen
departments|36|num
16|departments|of
reach|sales|subj
reach|$2 billion|obj
began|fans|subj
began|lining up|fc
lining up|fan|subj
lining up|theaters|at
theaters|may 3.|on
mobs|cheering|mod
greeted|mobs|subj
greeted|film|obj
film|it|as
opened|finally|mod-before
film|opened|vrel
opened|film|obj
mixed|reviews|obj
mixed|movie|with
movie|praised|vrel
praised|movie|obj
effects|its|gen
effects|special|nn
praised|effects|for
generated|computer|subj
generated|scenes|obj
brought in|it|subj
brought in|$100 million|obj
days|5|amount-value
$100 million|days|in
days|and|punc
days|$200 million|conj
$200 million|13|in
europeans|and|punc
europeans|japanese|conj
flew|europeans|subj
flew|america|to
america|opening|for
copies|pirated|mod
were|in|pred
were|hong kong|in
hong kong|week|in
version|asian|mod
opened|version|subj
opened|july 10|on
opened|joy|to
fans|japanese|mod
joy|fans|of
opened|but|mod
craze|anticipated|mod
craze|united kingdom|in
did|not|neg
but|materialize|comp1
materialize|craze|subj
