virus|west nile|nn
identified|first|amod
identified|virus|obj
identified|united states|in
united states|summer|in
summer|1999|of
identified|after|mod
after|began|comp1
began|birds|subj
began|dying|fc
dying|bird|subj
zoo|bronx|nn
near|zoo|obj
killed|virus|subj
killed|7|obj
killed|and|punc
killed|sickened|conj
sickened|virus|subj
sickened|77|obj
77|new york city|in
horses|long island|on
died|also|mod-before
died|horses|subj
birds|afflicted|mod
found|birds|obj
found|new jersey|in
new jersey|connecticut|conj
connecticut|and|punc
connecticut|baltimore|conj
appeared|again|mod-before
after|appeared|comp1
appeared|virus|subj
appeared|new york city|in
new york city|and|punc
new york city|connecticut|conj
new york city|then|pnmod
then|june|in
new york city|delaware|in
in|and|punc
in|in|conj
in|july|in
new york city|boston|in
victim|first|post
victim|human|mod
victim|2000|for
was|on|pred
was|staten island|on
began|virus|subj
began|spreading|mod
spreading|virus|subj
spreading|new york state|into
birds|afflicted|mod
found|birds|obj
found|rhode island|in
rhode island|august|in
in|and|punc
in|in|conj
in|baltimore|in
baltimore|and|punc
baltimore|philadelphia|conj
philadelphia|september|in
people|seventeen|nn
contracted|people|subj
contracted|disease|obj
died|one|subj
expected|virus|obj
expected|georgia|in
georgia|and|punc
georgia|north carolina|conj
states|17|num
states|eastern|mod
were|on|pred
were|alert|on
virus|west nile|nn
discovered|virus|obj
discovered|1937|in
discovered|uganda|in
strain|u.s.|nn
came from|probably|mod-before
came from|strain|subj
came from|israel|obj
transmitted|it|obj
transmitted|by|by-subj
transmitted|mosquitoes|by
birds|bite|nn
birds|infected|mod
mosquitoes|birds|whn
spread|then|mod-before
spread|birds|subj
spread|it|obj
birds|other|mod
spread|birds|to
birds|people|conj
people|and|punc
animals|other|mod
people|animals|conj
focused on|control|subj
focused on|detection|obj
elimination|mosquito|nn
detection|elimination|conj
elimination|and|punc
protection|personal|mod
elimination|protection|conj
consisted of|detection|subj
mosquitoes|testing|nn
consisted of|mosquitoes|obj
birds|dead|mod
mosquitoes|birds|conj
birds|and|punc
birds|people|conj
people|who|whn
appeared|people|subj
chickens|sentinel|nn
chickens|"|punc
kept|chickens|obj
coast|east|mod
kept|coast|down
kept|and|punc
kept|tested|conj
tested|chickens|obj
tested|weekly|mod
sprayed|insecticides|obj
areas|threatened|mod
sprayed|areas|over
placed|larvacides|obj
placed|water|in
install|people|subj
screens|window|nn
install|screens|obj
urged|stay|conj
stay|people|subj
stay|inside|desc
morning|early|mod
inside|morning|in
stay|and|punc
wear|evening|mod-before
stay|wear|conj
wear|people|subj
sleeves|long|mod
wear|sleeves|obj
sleeves|and|punc
sleeves|pants|conj
insect repellent|use|nn
insect repellent|deet|nn
sleeves|insect repellent|appo
water|standing|mod
remove|water|obj
remove|and|punc
remove|keep|conj
keep|grass|obj
keep|short|mod
