embassies|us|nn
bombings|embassies|of
embassies|kenya|in
kenya|and|punc
kenya|tanzania|conj
tanzania|august 1998|in
killed|bombings|subj
killed|224|obj
killed|and|punc
killed|injured|conj
injured|bombings|subj
injured|5,000|obj
5,000|kenya|in
injured|and|punc
injured|killed|conj
killed|bombings|subj
killed|11|obj
killed|and|punc
killed|injured|conj
injured|bombings|subj
injured|70|obj
70|tanzania|in
simultaneity|near|mod
simultaneity|attacks|of
indicated|simultaneity|subj
planning|careful|mod
indicated|planning|obj
planning|and|punc
coordination|close|mod
planning|coordination|conj
coordination|perpetrators|by
planning|attack|for
took|planning|subj
months|three|amount-value
took|months|obj
took|and|punc
took|carried out|conj
carried out|planning|obj
carried out|by|by-subj
group|egyptian islamic jihad|nn
carried out|group|by
group|linked|vrel
linked|group|obj
laden|osama|nn
laden|bin|nn
linked|laden|to
some|bombers|of
entered|some|subj
entered|kenya|obj
kenya|somali|through
somali|and|punc
somali|rwanda|conj
originated in|explosives|subj
originated in|middle east|obj
originated in|and|punc
originated in|brought|conj
brought|explosives|obj
brought|by|by-subj
brought|sea|by
sea|comoros islands|to
comoros islands|then|pnmod
then|tanzania|to
those|used|rel
used|kenya|in
went by|then|amod
went by|those|subj
went by|road|obj
road|nairobi|to
part|bomb|of
bomb|used|vrel
used|bomb|obj
used|embassy|at
embassy|salaam|in
assembled|part|obj
assembled|tomy spaares manufactures ltd|at
shop|metal-working|nn
tomy spaares manufactures ltd|shop|appo
truck|refrigerator|nn
transported|truck|subj
transported|bomb|obj
bomb|that|whn
detonated|bomb|obj
detonated|embassy|at
bomb|that|whn
destroyed|bomb|subj
destroyed|embassy|obj
embassy|nairobi|in
built|bomb|obj
built|house|at
house|rented|vrel
rented|house|obj
rented|outskirts|on
outskirts|city|of
city|man|by
man|identified|vrel
identified|man|obj
identified|haroun fazil|as
alleged|fazil|obj
alleged|driven|mod
driven|fazil|subj
truck|white|mod
truck|pickup|nn
driven|truck|obj
truck|embassy|to
embassy|day|on
day|bombing|of
bombing|lead|rel
lead|bombing|subj
lead|vehicle|obj
vehicle|carrying|rel
carrying|vehicle|subj
carrying|bomb|obj
he|and|punc
associates|his|gen
he|associates|conj
believed|he|obj
members|al-qaeda|of
indicted|all|in
men|17|num
indicted|men|obj
indicted|new york|in
new york|charges|on
charges|related|vrel
related|charges|obj
related|bombings|to
five|them|of
five|who|whn
are|still|guest
are|at large|pred
accused|five|obj
conspiring|five|subj
laden|osama|nn
laden|bin|nn
conspiring|laden|with
