virus|west nile|nn
detected|first|amod
detected|virus|obj
detected|united states|in
united states|august 1999|in
discovery|virus|of
occurred|discovery|subj
occurred|uganda|in
uganda|1937|in
found|years|for
found|virus|obj
found|only|mod
only|africa|in
africa|parts|conj
parts|asia|of
asia|and|punc
asia|eastern europe|conj
humans|birds|conj
birds|and|punc
birds|horses|conj
are|subject|pred
subject|disease|to
transmitted|virus|obj
transmitted|by|by-subj
transmitted|bites|by
mosquitoes|infected|mod
bites|mosquitoes|from
contacted|disease|obj
()|handling|by
handling|birds|obj
birds|disease|with
handling|or|punc
handling|died|conj
died|it|from
disease|discovered|vrel
discovered|disease|obj
discovered|queens|in
birds|infected|mod
us|birds|in
birds|israel|from
is|particular|since
strain|virus|nn
is|similar|pred
similar|that|to
is|virus|pred
virus|"|punc
virus|escaped|vrel
escaped|virus|obj
escaped|"|punc
escaped|sloan-kettering institute|from
sloan-kettering institute|where|wha
provided|virus|obj
treatments|experimental|mod
provided|treatments|for
60|over|num-mod
individuals|60|nn
individuals|new york|in
contacted|individuals|subj
contacted|disease|obj
disease|and|punc
disease|seven|conj
elderly|all|mod
spread|weeks|within
spread|disease|subj
new jersey|nearby|mod
spread|new jersey|to
new jersey|and|punc
new jersey|connecticut|conj
feared|scientists|subj
feared|that|c
appear|soon|amod
appear|virus|subj
appear|areas|in
areas|south|to
south|new york|of
new york|based|vrel
based|new york|obj
patterns|bird|nn
patterns|migratory|mod
based|patterns|on
killed|first year|within
first year|discovery|after
discovery|us|in
virus|west nile|nn
killed|virus|subj
killed|thousands|obj
birds|wild|mod
thousands|birds|of
birds|massachusetts|from
massachusetts|maryland|to
controlling|spread|obj
spread|west nile|of
is|dependent|pred
dependent|killing|upon
killing|virus|subj
killing|mosquitoes|obj
mosquitoes|infect|rel
infect|mosquitoes|obj
infect|that|subj
infect|virus|with
mosquito|spraying|nn
mosquito|likely|mod
mosquito|breeding|rel
breeding|mosquito|subj
breeding|areas|obj
is|done|pred
done|northeast|in
northeast|pesticides|with
pesticides|and|punc
pesticides|larvacides|conj
are|developed|pred
us|southern|mod
developed|us|in
us|spraying|for
spraying|anticipation|in
anticipation|spread|of
spread|virus|of
spraying|southward|mod
