blasted|august 7 , 1998 ,|on
bombings|coordinated|mod
blasted|bombings|subj
embassies|us|nn
blasted|embassies|obj
embassies|kenya|in
kenya|and|punc
kenya|tanzania|conj
250|more than|num-mod
people|250|nn
killed|people|obj
5,000|injured|vrel
injured|5,000|obj
5,000|most|appo-mod
most|them|of
5,000|kenyans|appo
kenyans|and|punc
kenyans|tanzanians|conj
killed|twelve americans|obj
officials|us|nn
officials|federal|mod
officials|law enforcement|nn
linked|tentatively|mod-before
linked|officials|subj
laden|osama|nn
laden|bin|nn
linked|laden|obj
bombings|two|nn
laden|bombings|to
islamic jihad|financed|vrel
financed|islamic jihad|obj
financed|by|by-subj
laden|bin|nn
financed|laden|by
suspected|also|amod
suspected|islamic jihad|obj
arrested|suspects|obj
weeks|two first|amount-value
arrested|weeks|within
weeks|blasts|after
blasts|khalid mohammed|appo
khalid mohammed|accused|vrel
accused|khalid mohammed|obj
accused|hurling|of
hurling|suspect|subj
hurling|grenade|obj
guards|security|nn
grenade|guards|at
guards|them|among
arrested|early|mod
suspects|arrested|mod
confessions|suspects|by
confirmed|confessions|subj
confirmed|suspicions|obj
suspicions|link|of
laden|bin|nn
link|laden|with
suspects|two|nn
suspects|khalid salim|conj
khalid salim|and|punc
khalid salim|mohammed saddiq odeh|conj
us|trial|for
police|local|mod
arrested|police|subj
suspects|other|mod
arrested|suspects|obj
were|soon|guest
were|determine|pred
determine|materials|obj
materials|and|punc
materials|methods|conj
methods|involved|vrel
involved|methods|obj
plot|bombing|nn
involved|plot|in
ingredients|bomb|nn
originated in|ingredients|subj
originated in|middle east|obj
sea|comoro islands|via
comoro islands|tanzania|to
assembled|bomb|obj
assembled|home|at
home|haroun fazil|of
assembled|comoro|of
device|explosive|nn
attached|then|amod
attached|device|obj
attached|vehicle|to
workshop|metal|mod
vehicle|workshop|in
workshop|owned|vrel
owned|workshop|obj
owned|by|by-subj
businessman|prominent|mod
businessman|salaam|nn
owned|businessman|by
businessman|tony lyimo|appo
bomb|packed|vrel
packed|bomb|obj
packed|batteries|with
batteries|and|punc
tanks|oxygen|nn
batteries|tanks|conj
tanks|make|rel
make|tank|subj
make|it|obj1
explosive|more|mod
make|explosive|desc
carried|bomb|obj
carried|compound|into
truck|refrigerator|nn
compound|truck|by
suspect|arrested|mod
suspect|mustafa mahmoud said ahmed|appo
gave|suspect|subj
gave|details|obj
details|bombing|of
carried|kenya|in
carried|bomb|obj
suzuki sumurai|white|mod
carried|suzuki sumurai|in
warning|he|subj
officials|us|nn
warning|officials|obj
officials|months|for
officials|attack|before
warning|saying|mod
saying|he|subj
saying|that|c
vehicles|three|nn
used|vehicles|obj
used|attack|in
