viruses|computer|nn
turned up|viruses|subj
part|just about|pre
turned up|part|in
part|world|of
viruses|and|punc
viruses|"|punc
viruses|worms|conj
come|"|punc
come|viruses|subj
come|names|with
names|happy 99|like
happy 99|melissa|conj
melissa|chernobyl|conj
c|killer|nn
chernobyl|c|conj
c|white lion|conj
white lion|and|punc
white lion|love bug|conj
systems|commercial|mod
damage|systems|to
systems|and|punc
systems|thousands|conj
computers|personal|nn
thousands|computers|of
computers|viruses|from
been|extensive|pred
been|and|punc
been|run into|conj
run into|damage|subj
run into|billions|obj
billions|dollars|of
erase|generally|amod
erase|virus|subj
drive|computer|gen
drive|hard|mod
erase|drive|obj
erase|and|punc
erase|prevent|conj
prevent|virus|subj
prevent|machine|obj
machine|restarted|from
does|worm|subj
damage|direct|mod
does|damage|obj
damage|computer|to
programs|and|punc
programs|attaches|conj
sent|message|subj
worms|and|punc
worms|viruses|conj
are|mostly|guest
are|spread|pred
spread|emails|by
emails|and|punc
emails|attachments|conj
are|thereto|mod
emails|that|whn
carry|emails|subj
viruses|infecting|mod
carry|viruses|obj
viruses|and|punc
viruses|worms|conj
are|in|pred
document|microsoft word|nn
are|document|in
document|and|punc
document|systems|conj
systems|that|whn
affected|systems|obj
affected|by|by-subj
affected|viruses|by
are|word 95|pred
word 95|97|conj
97|98|conj
98|2000|num
98|windows nt|conj
windows nt|outlook|conj
outlook|and|punc
outlook|outlook express|conj
useful|otherwise|mod
feature|useful|mod
feature|microsoft word|of
is|that|c
enables|it|subj
programs|macro|mod
enables|programs|obj
programs|scripts|appo
scripts|that|whn
trigger|scripts|subj
trigger|actions|obj
computer|host|nn
actions|computer|by
exploited|feature|obj
exploited|by|by-subj
exploited|hackers|by
hackers|introduce|rel
introduce|hacker|subj
introduce|worms|obj
david smith|aberdeen|of
arrested|david smith|obj
originating|david smith|subj
worm|melissa|nn
originating|worm|obj
virus|chernobyl|nn
known|virus|obj
known|taiwan|in
virus|cih|nn
taiwan|virus|as
virus|initials|for
chen ing-hau|its|gen
chen ing-hau|creator|nn
initials|chen ing-hau|of
worm|love bug|nn
attributed|worm|obj
couple|philippine|nn
attributed|couple|to
couple|rommel lamores|conj
rommel lamores|and|punc
rommel lamores|irene de guzman|conj
version|later|mod
deadly|more|mod
version|deadly|mod
version|love bug|of
originated in|version|subj
originated in|israel|obj
worm|explore|nn
originated in|also|amod
originated in|worm|subj
originated in|israel|obj
