is|precursor|pred
precursor|production|for
vx|deadly|mod
vx|nerve gas|nn
production|vx|of
traces|empta|of
found|traces|obj
plant|ugandan|mod
plant|pharmaceutical|mod
found|plant|near
plant|1998|in
bombed|us|subj
bombed|plant|obj
ties|sudan|gen
plant|ties|because of
ties|iraq|to
iraq|and|punc
laden|osama|nn
laden|bin|nn
iraq|laden|conj
papers|research|nn
although|discuss|comp1
discuss|papers|subj
discuss|using|mod
using|paper|subj
using|empta|obj
empta|produce|rel
produce|empta|subj
agents|anti-microbial|mod
produce|agents|obj
use|known|mod
use|industrial|mod
is|use|pred
plant|milwaukee|nn
produces|plant|subj
produces|some|obj
some|research|for
precursors|other|mod
precursors|vx|nn
trichloride|phosphorous|mod
are|trichloride|pred
pentasulfide|phosphorous|mod
trichloride|pentasulfide|conj
pentasulfide|and|punc
ethylamine|diisopropyl|nn
pentasulfide|ethylamine|conj
existed|probably|amod
existed|itself|subj
existed|us|in
us|russia|conj
russia|iran|conj
iran|syria|conj
syria|and|punc
syria|iraq|conj
was|used|pred
used|japanese|by
attack|1994|num
cult|attack|in
in|and|punc
in|in|conj
in|1998|in
found|cult|obj
warheads|iraqi|mod
found|warheads|on
site|weapons|nn
site|demolition|nn
warheads|site|at
tons|cp3poc12|of
cp3poc12|precursor|appo
precursor|sarin|to
sarin|and|punc
agents|other|mod
agents|nerve|nn
sarin|agents|conj
taken|tons|obj
facility|production|nn
taken|facility|from
facility|bosnia|in
bosnia|1992|in
yugoslavia|former|mod
cs|weaponized|mod
cs|sarin|conj
sarin|and|punc
sarin|bz|conj
ended up|probably|mod-before
ended up|weapons|subj
hands|serbian|mod
ended up|hands|in
used|bz|obj
used|kosovo|in
governs|chemical weapons treaty|subj
weapons|chemical|mod
governs|weapons|obj
items|schedule 1|nn
kill|only|mod-before
kill|items|subj
kill|people|obj
kill|and|punc
kill|prohibited|conj
prohibited|items|obj
items|schedule 2|nn
are|subject|pred
subject|inspections|to
people|four hundred|nn
involved|people|obj
involved|inspections|with
inspections|which|whn
include|inspections|subj
surveillance|camera|nn
include|surveillance|obj
materials|suspected|mod
are|destroyed|pred
monitored|destruction|obj
levied|sanctions|obj
levied|violators|on
attacks|nato|nn
are|possible|pred
governments|individual|mod
ban|also|mod-before
ban|governments|subj
ban|shipment|obj
chemicals|dual-use|mod
shipment|chemicals|of
us|and|punc
soviet union|former|mod
us|soviet union|conj
had|us|subj
stores|vast|mod
had|stores|obj
weapons|chemical|mod
stores|weapons|of
destroying|us|subj
destroying|its|obj
destroying|incinerators|at
incinerators|tooele|in
tooele|and|punc
tooele|johnston island|conj
johnston island|pacific|in
