bookselling|united states|in
changed|bookselling|subj
changed|dramatically|mod
dramatically|1990s|in
booksellers|independent|mod
hit|hardest|mod
been|hit|pred
hit|changes|by
claimed|1991|in
claimed|independents|subj
claimed|nearly|guest
claimed|third|obj
purchases|adult|mod
purchases|book|nn
third|purchases|of
years|six|amount-value
later|years|amount-value
share|their|gen
share|market|nn
was|nearly|guest
was|cut|pred
cut|half|in
was|down|mod
down|17%|to
aba|(|punc
american booksellers association|aba|abbrev
aba|)|punc
american booksellers association|that|whn
represents|american booksellers association|subj
saw|independents|nn
represents|saw|obj
membership|its|gen
saw|drop|rel
drop|saw|obj
drop|membership|subj
drop|5,200|from
less|3,500|than
booksellers|chain|nn
like|booksellers|subj
& noble and borders did increase market share by 3% during this same period but they too faced increasing challenges from price clubs and especially from online booksellers such as amazon.|barnes|nn
like|& noble and borders did increase market share by 3% during this same period but they too faced increasing challenges from price clubs and especially from online booksellers such as amazon.|obj
formed|aba|obj
formed|represent|mod
represent|aba|subj
booksellers|independent|mod
represent|booksellers|obj
filed|they|subj
filed|suit|obj
&noble when it made a bid to acquire the leading book wholesaler ingram book group.|barnes|nn
suit|&noble when it made a bid to acquire the leading book wholesaler ingram book group.|against
dropped|later|amod
dropped|bid|obj
dropped|opposition|because of
opposition|federal trade commission|from
dropped|but|punc
dropped|had|conj
had|bid|subj
gone through|it|obj
&noble could have optimized its own position by preferential channeling of book distribution through its stores to the detriment of the independents.|barnes|nn
continued|increase|to
share|its|gen
share|book|of
increase|market|rel
market|increase|obj
market|share|subj
chains|and|punc
chains|independents|conj
established|also|amod
established|chains|subj
sites|online|mod
established|sites|obj
&noble established an online venture that in at least one year lost money.|barnes|nn
established|also|mod-before
established|independents|subj
store|its own|gen
store|national|mod
store|online|mod
established|store|obj
sense|book|nn
store|sense|appo
established|stave|mod
stave|independent|subj
stave|off|guest
competition|fierce|mod
stave|competition|obj
competition|amazon.com|from
amazon.com|and|punc
amazon.com|barnesandnoble.com|conj
formed|also|mod-before
formed|they|subj
formed|bookfinder.com|obj
bookfinder.com|permit|rel
permit|bookfinder.com|subj
browsing|online|mod
permit|browsing|obj
browsing|inventories|of
inventories|thousands|of
bookshops|independent|mod
thousands|bookshops|of
