since|seized|comp1
seized|they|subj
seized|power|obj
power|1988|in
rulers|myanmar|gen
rulers|military|mod
used|rulers|subj
labor|forced|mod
used|labor|obj
labor|torture|conj
torture|and|punc
torture|rape|conj
rape|maintain|rel
maintain|rape|subj
maintain|power|obj
general|tin oo|person
general|top|mod
is|general|pred
general|regime|in
groups|15|num
groups|anti-government|mod
surrendered|groups|subj
surrendered|january 1998|as of
party|nld|nn
party|led|vrel
led|party|obj
led|by|by-subj
led|suu kyi|by
won|party|subj
elections|1990|num
won|elections|obj
honor|junta|subj
results|election|nn
honor|results|obj
suu kyi|nobel peace|nn
suu kyi|laureate|mod
demanded|suu kyi|subj
demanded|that|c
permitted|parliament|obj
permitted|convene|mod
convene|parliament|subj
convene|and|punc
convene|protested|conj
protested|release|for
release|political prisoners|of
arrests|estimated|mod
arrests|500-900|nn
arrests|political|mod
occurred|arrests|subj
occurred|months|in
months|preceding|rel
preceding|month|subj
anniversary|tenth|post
preceding|anniversary|obj
anniversary|takeover|of
preceding|including|mod
including|members|obj
members|absdf|of
absdf|led|vrel
led|absdf|obj
led|by|by-subj
led|ko thein|by
