announced|oprah winfrey|subj
announced|that|c
developing|she|subj
channel|tv|nn
developing|channel|obj
channel|named|vrel
named|channel|obj1
named|oxygen|obj2
developing|and|punc
developing|starting|conj
starting|she|subj
starting|magazine|obj
magazine|inform|rel
inform|magazine|subj
inform|women|obj
promotions|her|gen
promotions|book|nn
promotions|club|nn
promotions|tv|on
won|promotions|subj
won|her|obj1
medal|50th|mod
medal|anniversary|nn
won|medal|obj2
medal|national book foundation|from
discussion|latest|mod
discussion|book|nn
discussion|club|nn
was|about|pred
was|novel|about
court|federal|mod
court|appeals|nn
court|new orleans|in
ruled|court|subj
ruled|that|c
show|oprah winfrey|subj
scare|mad|mod
scare|cow|nn
scare|disease|nn
information|false|mod
give|information|obj
give|or|punc
give|defame|conj
producers|cattle|nn
defame|producers|obj
received|oprah|subj
received|praise|obj
praise|teaching|for
teaching|oprah|subj
teaching|class|obj
class|northwestern university|at
northwestern university|but|punc
ranking|her|gen
ranking|show|nn
northwestern university|ranking|conj
ranking|dropped|vrel
dropped|ranking|obj
dropped|slightly|mod
performance|below-expectations|nn
slightly|performance|after
in|"|punc
performance|beloved|in
