days|19|amount-value
hours|21|amount-value
days|hours|conj
hours|and|punc
minutes|47|amount-value
hours|minutes|conj
team|swiss-british|nn
team|balloonist|nn
team|piccard|of
piccard|and|punc
piccard|jones|conj
minutes|landed|rel
landed|minutes|obj
landed|team|subj
landed|early|mod
early|march 21|on
sands|saharan|nn
landed|sands|in
egypt|southern|mod
sands|egypt|of
winds|unfavorable|mod
prevented|winds|subj
landing|their|gen
landing|hoped-for|mod
prevented|landing|obj
landing|pyramids|near
crossed|they|subj
degrees|9|amount-value
finish line|degrees|nn
finish line|longitude|nn
crossed|finish line|obj
crossed|day|mod
crossed|before|mod
crossed|setting|mod
setting|they|subj
setting|record|obj1
nonstop|first|post
record|nonstop|for
circumnavigation|hot-air balloon|nn
setting|circumnavigation|obj2
circumnavigation|globe|of
feat|their|gen
awarded|feat|for
awarded|anheuser-busch corporation|subj
awarded|balloonists|obj1
awarded|cup|obj2
cup|and|punc
money|$1million|nn
money|prize|nn
cup|money|conj
money|some|whn
some|money|of
use|some|obj
use|they|subj
use|start|mod
start|they|subj
start|winds|obj
charity|hope foundation|nn
winds|charity|of
award|international olympic committee|subj
award|them|obj1
award|olympic order|obj2
