earthquakes|two|nn
earthquakes|consecutive|mod
earthquakes|that|whn
struck|earthquakes|subj
struck|turkey|obj
turkey|3:00 am|about
turkey|17 august 1999|on
lasted|earthquakes|subj
seconds|45|amount-value
lasted|seconds|obj
epicenter|tremors|of
was|near|pred
was|izmit|near
izmit|east|pnmod
east|istanbul|of
toll|death|nn
surpassed|toll|subj
surpassed|12,000|obj
others|33,405|num
reported|others|obj
loss|economic|mod
estimated|loss|obj
estimated|$20|at
$20|$40 billion|to
factories|idle|mod
factories|damaged|mod
cause|factories|subj
cause|loss|obj
loss|$300 million|of
needed|cash|obj
needed|repair|mod
repair|cash|subj
infrastructure|basic|mod
repair|infrastructure|obj
hit|area|nn
provides|hit|subj
half|almost|mod
provides|half|guest
revenue|tax|nn
provides|revenue|obj
survivors|200,000|num
survivors|homeless|mod
are|desperate|pred
desperate|refuge|for
united states|and|punc
plan|holland|nn
united states|plan|conj
plan|send|rel
send|plan|subj
shelters|prefabricated|mod
send|shelters|in
shelters|and|punc
tents|all-weather|mod
shelters|tents|conj
