days|19|amount-value
hours|21|amount-value
days|hours|conj
hours|and|punc
minutes|55|amount-value
hours|minutes|conj
bertrand piccard|and|punc
bertrand piccard|brian jones|conj
ended|bertrand piccard|subj
flight|their|gen
flight|29,056-mile|mod
flight|balloon|nn
ended|flight|obj
flight|sands|in
sahara desert|egypt|gen
sands|sahara desert|of
people|first|post
achieved|people|as
people|circumnavigate|rel
circumnavigate|people|subj
circumnavigate|earth|obj
earth|hot-air balloon|in
achieved|two|subj
said|what|obj
said|promoters|subj
achieved|was|fc
milestone|last|post
milestone|great|mod
was|milestone|pred
milestone|aviation|of
was|and|punc
was|received|conj
received|fin|subj
received|awards|obj
awards|international olympic committee|from
international olympic committee|and|punc
international olympic committee|federation aeronautique internationale|conj
federation aeronautique internationale|as|punc
federation aeronautique internationale|well|punc
federation aeronautique internationale|as|punc
prize|$1 million|nn
federation aeronautique internationale|prize|conj
prize|anheuser-bush co.|from
helium/hot|their|gen
air|helium/hot|subj
balloon--|hybrid|mod
air|balloon--|obj
3--|breitling|nn
3--|orbiter|nn
housed|permanently|amod
housed|3--|obj
housed|air|at
air|and|punc
museum|space|nn
air|museum|conj
museum|washington|in
washington|dc|appo
