cause|crash|of
crash|egyptair flight 990|of
egyptair flight 990|nantucket|off
1999 may|october|nn
nantucket|1999 may|in
known|never|mod-before
known|cause|obj
certainty|absolute|mod
known|certainty|with
boeing|767|num
route|en|nn
was|route|pred
route|jfk airport|from
jfk airport|egypt|to
were|survivors|pred
tracks|radar|nn
tracks|flight|of
flight|its|during
minutes|final|mod
indicated|minutes|mod-before
indicated|tracks|subj
indicated|went into|fc
went into|plane|subj
went into|dive|obj
went into|but|punc
went into|climbed|conj
climbed|plane|subj
climbed|again|mod
climbed|before|mod
going into|plane|subj
steep|extremely|mod
dive|steep|mod
going into|dive|obj
dive|breaking up|during
breaking up|plane|of
before|occurred|comp1
autopilot|plane|gen
disconnected|autopilot|obj
disconnected|either|mod
disconnected|deliberately|mod
before|descended|comp1
descended|plane|subj
reverser|one|nn
reverser|thrust|nn
deactivated|previously|amod
deactivated|reverser|obj
deactivated|problem|because of
was|speculation|pred
speculation|that|c
reverser|thrust|nn
deployed|speculation|obj
deployed|reverser|subj
stopped working|also|amod
stopped working|transponder|subj
pilot|nor|punc
pilot|co-pilot|conj
sent|pilot|subj
message|distress|nn
sent|message|obj
box|one|nn
box|black|nn
data|box|from
showed|data|subj
showed|that|c
switched off|engines|obj
switched off|cabin|from
elevators|which|whn
raise|elevators|subj
nose|plane|gen
raise|nose|obj
were|in|pred
setting|uneven|mod
were|setting|in
possible|crew|for
crew|make|rel
make|crew|subj
recordings|cockpit|nn
recordings|voice|nn
indicated|recordings|subj
indicated|that|c
uttered|someone|subj
uttered|prayer|obj
prayer|arabic|in
uttered|just|mod
just|autopilot|before
autopilot|disengaged|vrel
disengaged|autopilot|obj
disengaged|raising|mod
raising|someone|subj
raising|questions|obj
terrorist|possible|mod
questions|terrorist|of
terrorist|or|punc
act|suicide|nn
terrorist|act|conj
theory|terrorist|mod
raised|theory|obj
raised|because|mod
officers|egyptian|mod
officers|army|nn
because|were|comp1
were|on|pred
were|board|on
copilot|plane|gen
having|copilot|subj
having|problems|obj
having|and|punc
having|exhibited|conj
exhibited|copilot|subj
behavior|strange|mod
exhibited|behavior|obj1
behavior|new york|in
exhibited|hotel|obj2
hotel|flight|before
flight|suggesting|rel
suggesting|flight|subj
crashed|deliberately|amod
suggesting|crashed|fc
crashed|he|subj
crashed|plane|obj
authorities|egyptian|mod
discounted|authorities|subj
theory|suicide|nn
discounted|theory|obj
discounted|and|punc
discounted|raised|conj
raised|authorities|subj
raised|possibility|obj
possibility|that|c
problems|plane|gen
caused|problems|obj
caused|by|by-subj
interference|electromagnetic|mod
caused|interference|by
radars|military|mod
interference|radars|from
