ii-class|russian|mod
ii-class|oscar|nn
submarine|atomic|mod
submarine|powered|mod
ii-class|submarine|appo
submarine|kursk|appo
sank in|ii-class|subj
sank in|barents sea|obj
barents sea|august 12 , 2000|on
exercise|naval|mod
barents sea|exercise|during
one|russia|of
's|largest|pred
commissioned|1996|in
crew|118|of
began|russians|subj
effort|massive|mod
effort|rescue|nn
began|effort|obj
effort|august 13|on
began|and|punc
began|announced|conj
announced|russians|subj
announced|loss|obj
day|next|post
announced|day|mod
announced|when|wha
vessels|15|num
vessels|and|punc
vessels|warships|conj
involved|vessels|obj
involved|search|in
efforts|russian|mod
efforts|reach|rel
reach|effort|subj
reach|submarine|obj
submarine|using|rel
using|submarine|subj
capsules|underwater|mod
using|capsules|obj
failed|efforts|subj
talked|russia|subj
officials|nato|nn
talked|officials|to
turned down|russia|subj
offer|french|nn
turned down|offer|obj
offer|help|of
help|and|punc
offer|germany|gen
help|offer|conj
offer|medical specialists|of
asked|august 16|on
asked|russia|subj
asked|britain|obj
britain|and|punc
britain|norway|conj
norway|send|rel
send|norway|subj
submarine|rescue|nn
send|submarine|obj
submarine|and|punc
submarine|divers|conj
teams|rescue|nn
arrived at|teams|subj
arrived at|scene|obj
scene|august 19|on
arrived at|and|punc
arrived at|began|conj
began|teams|subj
began|descent|obj
descent|kursk|to
kursk|20th|on
confirmed|russians|subj
confirmed|all|obj
were|dead|pred
dead|21st|on
causes|various|mod
causes|disaster|of
presented|causes|obj
believed|united states|subj
torpedoes|kursk|gen
one|torpedoes|of
believed|misfired|fc
misfired|one|subj
misfired|causing|mod
causing|one|subj
explosion|massive|mod
causing|explosion|obj
officials|russian|mod
speculated|officials|subj
speculated|that|c
collided|kursk|subj
collided|vessel|with
vessel|probably|appo-mod
submarine|foreign|mod
vessel|submarine|appo
mine|world war ii|nn
source|one|nn
source|german|mod
said|source|subj
missile|russian|mod
missile|anti-submarine|mod
said|hit|fc
hit|missile|subj
hit|it|obj
vowed|putin|subj
vowed|retrieve|fc
retrieve|putin|subj
retrieve|bodies|obj
bodies|crew|of
crew|and|punc
crew|vessel|conj
made|plans|obj
company|unnamed|mod
company|norwegian|mod
made|company|for
company|begin|rel
begin|company|subj
operation|body|nn
operation|retrieval|nn
begin|operation|obj
operation|october 10|on
hoped|russians|subj
hoped|raise|fc
raise|russian|subj
raise|boat|obj
boat|summer|in
summer|2001|of
cost|anticipated|mod
summer|cost|at
cost|$45 million|of
