jimmy carter|-president|nn
been|champion|pred
peace|world|nn
champion|peace|for
peace|and|punc
rights|human|nn
peace|rights|conj
rights|leaving office|since
leaving office|jimmy carter|subj
met with|he|subj
dictators|various|mod
met with|dictators|obj
met with|including|mod
including|he|subj
including|yasser arafat|obj
il-sung|kim|nn
yasser arafat|il-sung|conj
il-sung|and|punc
il-sung|daniel ortega|conj
including|plead|conj
plead|he|subj
plead|case|obj
case|peace|for
plead|and|punc
plead|obtain|conj
obtain|he|subj
obtain|release|obj
political prisoners|50,000|num
release|political prisoners|of
established|addition|in
he|and|punc
wife|his|gen
he|wife|conj
he|rosalynn|appo
established|he|subj
established|carter center|obj
carter center|1982|in
focused|center|obj
focused|efforts|on
efforts|ensure|rel
ensure|effort|subj
elections|free|mod
ensure|elections|obj
ensure|and|punc
ensure|fight|conj
fight|effort|subj
diseases|world|nn
fight|diseases|obj
delegations|carter center|from
led|frequently|amod
carter center|led|vrel
led|carter center|obj
led|by|by-subj
led|president|by
president|carter|person
observed|delegations|subj
all|elections|nn
observed|all|obj
all|world|around
observed|elections|obj
10|at least|num-mod
central|10|nn
observed|central|in
central|and|punc
central|south american countries|conj
observed|including|mod
including|election|subj
including|mexico|obj
mexico|panama|conj
panama|and|punc
panama|peru|conj
initiated|1998|in
initiated|center|subj
initiated|project|obj
project|called|vrel
called|project|obj1
called|"|punc
called|transparency for growth in the americas|desc
delegations|center|gen
observed|delegations|subj
observed|elections|obj
elections|china|in
china|(|punc
china|where|wha
fosters|carter|subj
policy|his|gen
policy|one-china|nn
fosters|policy|obj
policy|)|punc
policy|indonesia|conj
indonesia|nigeria|conj
nigeria|liberia|conj
liberia|and|punc
liberia|mozambique|conj
committed|1987|since
committed|center|obj
committed|eradication|to
blindness|river|nn
eradication|blindness|of
blindness|africa|in
caused|disease|obj
caused|by|by-subj
flies|black|nn
caused|flies|by
flies|and|punc
flies|18 million|conj
infected|people|obj
infected|by|by-subj
infected|1999|by
fighting|also|amod
fighting|center|subj
disease|guinea-worm|nn
fighting|disease|obj
disease|africa|in
africa|and|punc
africa|asia|conj
3 million|estimated|mod
infested|people|obj
infested|year|mod
year|roundworm|with
recognized|2000|in
recognized|center|subj
recognized|pakistan|obj
nation|first|post
nation|asian|nn
being|nation|pred
nation|eradicate|rel
eradicate|nation|subj
eradicate|disease|obj
initiated|1999|in
initiated|center|subj
program|its|gen
program|first|post
initiated|program|obj
program|aimed at|vrel
aimed at|program|obj
aimed at|eradicating|mod
eradicating|center|subj
eradicating|trachoma|obj
disease|eye|nn
trachoma|disease|conj
disease|caused|vrel
caused|by|by-subj
flies|black|nn
caused|flies|by
flies|which|whn
blinded|flies|subj
people|6 million|nn
blinded|people|obj
people|and|punc
millions|infected|mod
people|millions|conj
eradicating|more|mod
